import { db } from "./db";
import { venues } from "@shared/schema";
import { eq } from "drizzle-orm";
import { nanoid } from "nanoid";

const venuesData = [
  // Luxury Hotels & Resorts
  {
    name: "The Ritz-Carlton Jeddah",
    nameAr: "فندق ريتز كارلتون جدة",
    city: "Jeddah",
    location: "King Fahad Fountain, Prince Sultan Road",
    description: "Luxury palace hotel with French-inspired gardens, offering two main ballrooms that can host 1,000+ guests each with Red Sea views",
    descriptionAr: "فندق فخم يطل على نافورة الملك فهد مع حدائق فرنسية وقاعتين رئيسيتين تتسع لأكثر من 1000 ضيف",
    venueType: "hotel",
    capacity: 2000,
    imageUrl: "https://images.marriott.com/marriottassets/marriott/JEDRJ/jedrj-ballroom-0086-hor-wide.jpg",
    imageUrls: [
      "https://images.marriott.com/marriottassets/marriott/JEDRJ/jedrj-exterior-0022-hor-wide.jpg",
      "https://images.marriott.com/marriottassets/marriott/JEDRJ/jedrj-ballroom-0086-hor-wide.jpg"
    ],
    amenities: ["Valet Parking", "Ballrooms", "Wedding Planning", "Catering", "AV Equipment", "Red Sea Views"],
    contactPhone: "+966-12-651-2000",
    contactEmail: "events.jeddah@ritzcarlton.com",
    website: "https://www.ritzcarlton.com/en/hotels/jedrj-the-ritz-carlton-jeddah/events/",
    priceRange: "2000-5000 SAR per event",
    rating: 4.8,
    verified: true,
  },
  {
    name: "InterContinental Jeddah",
    nameAr: "انتركونتيننتال جدة",
    city: "Jeddah",
    location: "Al Hamra Corniche",
    description: "Luxury hotel on the Corniche with 13 venues accommodating up to 1,150 guests, featuring Al Sultan Ballroom with Red Sea views",
    descriptionAr: "فندق فخم على الكورنيش مع 13 مكاناً يتسع لـ 1150 ضيف مع قاعة السلطان المطلة على البحر الأحمر",
    venueType: "hotel",
    capacity: 1150,
    imageUrl: "https://www.ihg.com/intercontinental/content/gb/en/hotels/jedha/overview/_jcr_content/brand-header/brand-header-image.img.jpg",
    imageUrls: [
      "https://www.ihg.com/intercontinental/content/gb/en/hotels/jedha/overview/_jcr_content/brand-header/brand-header-image.img.jpg"
    ],
    amenities: ["Al Sultan Ballroom", "Red Sea Views", "Ground Floor Access", "Dedicated Parking", "8 Meeting Rooms"],
    contactPhone: "+966-12-661-8888",
    contactEmail: "jedha@ihg.com",
    website: "https://www.ihg.com/intercontinental/hotels/gb/en/jeddah/jedha/hoteldetail/meetings-events",
    priceRange: "1500-4000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Park Hyatt Jeddah Marina Club & Spa",
    nameAr: "بارك حياة جدة مارينا",
    city: "Jeddah",
    location: "Marina Corniche",
    description: "Luxury marina hotel with Lazurde Conventions Centre featuring over 2,500 sq meters of event space and 800 sq meter ballroom",
    descriptionAr: "فندق مارينا فخم مع مركز لازوردي للمؤتمرات بمساحة أكثر من 2500 متر مربع وقاعة رقص 800 متر مربع",
    venueType: "hotel",
    capacity: 1000,
    imageUrl: "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/09/23/1130/JEDPH-P0765-Marina-Views.jpg",
    imageUrls: [
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/09/23/1130/JEDPH-P0765-Marina-Views.jpg"
    ],
    amenities: ["Marina Views", "8 Meeting Rooms", "Ballroom", "Wedding Coordination", "Private Entrances", "Marble Foyer"],
    contactPhone: "+966-12-263-7777",
    contactEmail: "jedph.events@hyatt.com",
    website: "https://www.hyatt.com/en-US/hotel/saudi-arabia/park-hyatt-jeddah-marina-club-and-spa/jedph/special-events",
    priceRange: "1800-4500 SAR per event",
    rating: 4.7,
    verified: true,
  },
  {
    name: "Hilton Jeddah Hotel",
    nameAr: "هيلتون جدة",
    city: "Jeddah",
    location: "Jeddah Corniche",
    description: "Award-winning MICE facilities with 55,434 sq ft of event space for up to 3,500 guests, featuring Hilton Hall and Al Qasr Ballroom",
    descriptionAr: "مرافق حائزة على جوائز مع 55434 قدم مربع من مساحة الأحداث لما يصل إلى 3500 ضيف",
    venueType: "hotel",
    capacity: 3500,
    imageUrl: "https://www.hilton.com/im/en/JEDHIHI/17834314/jedhihi-exterior-0041-hor-wide.jpg",
    imageUrls: [
      "https://www.hilton.com/im/en/JEDHIHI/17834314/jedhihi-exterior-0041-hor-wide.jpg"
    ],
    amenities: ["11 Meeting Rooms", "Conference Center", "Ocean Views", "Business Center", "Express Check-in", "Outdoor Event Areas"],
    contactPhone: "+966-12-654-0000",
    contactEmail: "jeddah.events@hilton.com",
    website: "https://www.hilton.com/en/hotels/jedhihi-jeddah-hilton-hotel/events/",
    priceRange: "2500-6000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Sheraton Jeddah Hotel",
    nameAr: "شيراتون جدة",
    city: "Jeddah",
    location: "Jeddah Corniche",
    description: "Premium hotel with 7 distinctive event spaces accommodating up to 1,000 guests including private-access ballroom",
    descriptionAr: "فندق فاخر مع 7 مساحات مميزة للأحداث تتسع لما يصل إلى 1000 ضيف",
    venueType: "hotel",
    capacity: 1000,
    imageUrl: "https://cache.marriott.com/marriottassets/marriott/JEDSI/jedsi-exterior-0065-hor-wide.jpg",
    imageUrls: [
      "https://cache.marriott.com/marriottassets/marriott/JEDSI/jedsi-exterior-0065-hor-wide.jpg"
    ],
    amenities: ["7 Event Spaces", "13,000+ sq ft", "Private Ballroom", "Social Occasions", "Professional Planning"],
    contactPhone: "+966-12-699-9999",
    contactEmail: "jedsi.events@sheraton.com",
    website: "https://www.marriott.com/en-us/hotels/jedsi-sheraton-jeddah-hotel/events/",
    priceRange: "1800-4200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  
  // Wedding Halls & Ballrooms
  {
    name: "Al Malekat Palace Hall",
    nameAr: "قاعة قصر الملكات",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Royal-style wedding hall with luxurious crystal chandeliers and elegant decor, perfect for grand celebrations",
    descriptionAr: "قاعة أفراح بطراز ملكي مع ثريات كريستالية فاخرة وديكور أنيق، مثالية للاحتفالات الكبيرة",
    venueType: "wedding_hall",
    capacity: 500,
    imageUrl: "https://example.com/al-malekat-palace.jpg",
    imageUrls: [
      "https://example.com/al-malekat-palace-main.jpg",
      "https://example.com/al-malekat-palace-interior.jpg"
    ],
    amenities: ["Crystal Chandeliers", "Royal Decor", "Bridal Suite", "Valet Parking", "Wedding Planning"],
    contactPhone: "+966-12-234-5678",
    contactEmail: "info@almalekatpalace.com",
    website: "https://www.almalekatpalace.com",
    priceRange: "3000-8000 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Al Embratora Hall",
    nameAr: "قاعة الإمبراطورة",
    city: "Jeddah",
    location: "Al Zahra District",
    description: "Ultra-glamorous wedding venue fit for royalty with luxurious crystal chandeliers, sculptured ceilings, and modern sound system",
    descriptionAr: "قاعة أفراح فائقة الفخامة تليق بالملوك مع ثريات كريستالية فاخرة وأسقف منحوتة ونظام صوتي حديث",
    venueType: "wedding_hall",
    capacity: 600,
    imageUrl: "https://example.com/al-embratora.jpg",
    imageUrls: [
      "https://example.com/al-embratora-main.jpg"
    ],
    amenities: ["Crystal Chandeliers", "Sculptured Ceilings", "Modern Sound System", "Sumptuous Pillars", "Elite Venue"],
    contactPhone: "+966-12-345-6789",
    contactEmail: "info@alembratorahall.com",
    website: "https://www.alembratorahall.com",
    priceRange: "4000-10000 SAR per event",
    rating: 4.7,
    verified: true,
  },
  {
    name: "Leylaty Wedding Hall",
    nameAr: "قاعة ليلاتي للأفراح",
    city: "Jeddah",
    location: "Al Khaldiya, Sari Street",
    description: "Unique and elegant wedding hall with fancy chandeliers and sophisticated decor, perfect for large celebrations",
    descriptionAr: "قاعة أفراح فريدة وأنيقة مع ثريات فاخرة وديكور راقي، مثالية للاحتفالات الكبيرة",
    venueType: "wedding_hall",
    capacity: 400,
    imageUrl: "https://example.com/leylaty-hall.jpg",
    imageUrls: [
      "https://example.com/leylaty-main.jpg"
    ],
    amenities: ["Fancy Chandeliers", "Unique Decor", "Large Capacity", "Professional Service", "Al Khaldiya Location"],
    contactPhone: "+966-12-456-7890",
    contactEmail: "info@leylatyhall.com",
    website: "https://www.leylatyhall.com",
    priceRange: "2500-6000 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Nasayem Layl Hall",
    nameAr: "قاعة نسائم الليل",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Elegant and classic wedding venue with beautiful kosha decorations, accommodating over 400 guests",
    descriptionAr: "قاعة أفراح أنيقة وكلاسيكية مع زينة كوشة جميلة، تتسع لأكثر من 400 ضيف",
    venueType: "wedding_hall",
    capacity: 400,
    imageUrl: "https://example.com/nasayem-layl.jpg",
    imageUrls: [
      "https://example.com/nasayem-layl-main.jpg"
    ],
    amenities: ["Kosha Decorations", "Classic Design", "Large Capacity", "Beautiful Interiors", "Professional Service"],
    contactPhone: "+966-12-567-8901",
    contactEmail: "info@nasayemlaylhall.com",
    website: "https://www.nasayemlaylhall.com",
    priceRange: "2000-5500 SAR per event",
    rating: 4.2,
    verified: true,
  },
  
  // Cultural Centers & Museums
  {
    name: "Nassif House Museum",
    nameAr: "متحف بيت نصيف",
    city: "Jeddah",
    location: "Al-Balad, Al Dhahab Street",
    description: "Historic cultural center in Old Jeddah with 106 rooms featuring Ottoman Turkish architectural style, perfect for cultural events and exhibitions",
    descriptionAr: "مركز ثقافي تاريخي في جدة القديمة مع 106 غرفة بالطراز المعماري التركي العثماني، مثالي للأحداث الثقافية والمعارض",
    venueType: "cultural_center",
    capacity: 200,
    imageUrl: "https://example.com/nassif-house.jpg",
    imageUrls: [
      "https://example.com/nassif-house-main.jpg",
      "https://example.com/nassif-house-courtyard.jpg"
    ],
    amenities: ["Historic Architecture", "Cultural Programming", "Art Exhibitions", "Traditional Crafts", "Library", "Courtyard"],
    contactPhone: "+966-12-678-9012",
    contactEmail: "info@nassifhouse.gov.sa",
    website: "https://www.nassifhouse.gov.sa",
    priceRange: "500-2000 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Darat Safeya Binzagr",
    nameAr: "دارة صفية بن زقر",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Art gallery and cultural center showcasing Saudi and Hijazi heritage through art, featuring extensive research library",
    descriptionAr: "معرض فني ومركز ثقافي يعرض التراث السعودي والحجازي من خلال الفن، مع مكتبة بحثية واسعة",
    venueType: "cultural_center",
    capacity: 150,
    imageUrl: "https://example.com/darat-safeya.jpg",
    imageUrls: [
      "https://example.com/darat-safeya-main.jpg"
    ],
    amenities: ["Art Exhibitions", "Research Library", "Saudi Heritage", "Hijazi Art", "Cultural Events"],
    contactPhone: "+966-12-789-0123",
    contactEmail: "info@daratsafeya.com",
    website: "https://www.daratsafeya.com",
    priceRange: "800-2500 SAR per event",
    rating: 4.3,
    verified: true,
  },
  
  // Shopping Mall Venues
  {
    name: "Red Sea Mall Conference Center",
    nameAr: "مركز مؤتمرات البحر الأحمر مول",
    city: "Jeddah",
    location: "Red Sea Mall, Prince Abdulmajeed Street",
    description: "Modern conference facilities within Red Sea Mall, perfect for corporate events and business meetings",
    descriptionAr: "مرافق مؤتمرات حديثة داخل البحر الأحمر مول، مثالية للفعاليات المؤسسية والاجتماعات التجارية",
    venueType: "mall",
    capacity: 300,
    imageUrl: "https://example.com/red-sea-mall-conference.jpg",
    imageUrls: [
      "https://example.com/red-sea-mall-main.jpg"
    ],
    amenities: ["Mall Location", "Corporate Events", "Business Meetings", "Modern Facilities", "Easy Access"],
    contactPhone: "+966-12-890-1234",
    contactEmail: "events@redseamall.com",
    website: "https://www.redseamall.com/events",
    priceRange: "1000-3000 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "Stars Avenue Mall Event Space",
    nameAr: "مساحة فعاليات ستارز أفينيو مول",
    city: "Jeddah",
    location: "King Abdulaziz Road, Al Zahra District",
    description: "4-story luxury mall with covered boulevard featuring facilities for weekend bazaars and special festivities",
    descriptionAr: "مول فاخر من 4 طوابق مع شارع مغطى يضم مرافق للبازارات الأسبوعية والفعاليات الخاصة",
    venueType: "mall",
    capacity: 250,
    imageUrl: "https://example.com/stars-avenue-events.jpg",
    imageUrls: [
      "https://example.com/stars-avenue-main.jpg"
    ],
    amenities: ["Weekend Bazaars", "Special Events", "Covered Boulevard", "Luxury Mall", "Al Fresco Cafes"],
    contactPhone: "+966-12-901-2345",
    contactEmail: "events@starsavenuemall.com",
    website: "https://www.starsavenuemall.com/events",
    priceRange: "800-2200 SAR per event",
    rating: 4.0,
    verified: true,
  },
  
  // Convention Centers
  {
    name: "Jeddah International Exhibition & Conference Center",
    nameAr: "مركز جدة الدولي للمعارض والمؤتمرات",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Largest corporate event venue in Saudi Arabia with 40,000 sq meters total area and 10,000 sq meters indoor event space",
    descriptionAr: "أكبر مكان للفعاليات المؤسسية في السعودية بمساحة إجمالية 40000 متر مربع و10000 متر مربع مساحة داخلية",
    venueType: "convention_center",
    capacity: 5000,
    imageUrl: "https://example.com/jiecc.jpg",
    imageUrls: [
      "https://example.com/jiecc-main.jpg",
      "https://example.com/jiecc-interior.jpg"
    ],
    amenities: ["Exhibition Halls", "Conference Rooms", "Advanced AV Technology", "High-speed Internet", "Outdoor Areas"],
    contactPhone: "+966-12-012-3456",
    contactEmail: "info@jiecc.com.sa",
    website: "https://www.jiecc.com.sa",
    priceRange: "5000-15000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  
  // Additional Luxury Hotels
  {
    name: "Shangri-La Jeddah",
    nameAr: "شانغريلا جدة",
    city: "Jeddah",
    location: "Prince Sultan Road",
    description: "Luxury hotel with 10 meeting rooms featuring latest AV technology and LED screens with bespoke event needs",
    descriptionAr: "فندق فاخر مع 10 غرف اجتماعات مع أحدث تقنيات الصوت والمرئيات وشاشات LED",
    venueType: "hotel",
    capacity: 600,
    imageUrl: "https://example.com/shangri-la-jeddah.jpg",
    imageUrls: [
      "https://example.com/shangri-la-exterior.jpg"
    ],
    amenities: ["10 Meeting Rooms", "Latest AV Technology", "LED Screens", "Private F&B Service", "Professional Boardrooms"],
    contactPhone: "+966-12-659-8888",
    contactEmail: "jeddah@shangri-la.com",
    website: "https://www.shangri-la.com/jeddah/shangrila/meetings-events/",
    priceRange: "1400-3800 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Rosewood Jeddah",
    nameAr: "روزوود جدة",
    city: "Jeddah",
    location: "Jeddah Corniche",
    description: "Ultra-luxury hotel with 8 exceptional meeting venues on the Corniche with refined design and elegant backdrop",
    descriptionAr: "فندق فاخر جداً مع 8 أماكن اجتماعات استثنائية على الكورنيش بتصميم راقي",
    venueType: "hotel",
    capacity: 400,
    imageUrl: "https://example.com/rosewood-jeddah.jpg",
    imageUrls: [
      "https://example.com/rosewood-facade.jpg"
    ],
    amenities: ["8 Meeting Venues", "Corniche Views", "Private Dining", "Luxury Setting", "Refined Design"],
    contactPhone: "+966-12-263-4444",
    contactEmail: "jeddah@rosewoodhotels.com",
    website: "https://www.rosewoodhotels.com/en/jeddah/meetings-and-events",
    priceRange: "2000-5500 SAR per event",
    rating: 4.8,
    verified: true,
  },
  
  // More Luxury Hotels
  {
    name: "Assila, a Luxury Collection Hotel",
    nameAr: "أسيلة، فندق مجموعة لاكشري",
    city: "Jeddah",
    location: "Prince Mohammed bin Abdulaziz Street (Tahlia Street)",
    description: "Five-star luxury hotel in Central Business District with meeting and event spaces, rooftop pool and spa",
    descriptionAr: "فندق خمس نجوم فاخر في منطقة الأعمال المركزية مع مساحات للاجتماعات والأحداث",
    venueType: "hotel",
    capacity: 500,
    imageUrl: "https://cache.marriott.com/marriottassets/marriott/JEDLA/jedla-exterior-0066-hor-wide.jpg",
    imageUrls: ["https://cache.marriott.com/marriottassets/marriott/JEDLA/jedla-exterior-0066-hor-wide.jpg"],
    amenities: ["Meeting Spaces", "Rooftop Pool", "Full-Service Spa", "Tahlia Street Location", "5 Restaurants"],
    contactPhone: "+966-12-293-8888",
    contactEmail: "jedla@luxurycollection.com",
    website: "https://www.marriott.com/en-us/hotels/jedla-assila-a-luxury-collection-hotel-jeddah/events/",
    priceRange: "1600-4000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Movenpick Hotel Tahlia Jeddah",
    nameAr: "موڤنبيك تاليا جدة",
    city: "Jeddah",
    location: "Prince Mohammed Bin Abdulaziz Street",
    description: "5-star luxury hotel with 7 meeting rooms for up to 150 guests, featuring modern technology",
    descriptionAr: "فندق 5 نجوم فاخر مع 7 غرف اجتماعات لما يصل إلى 150 ضيف مع تقنية حديثة",
    venueType: "hotel",
    capacity: 150,
    imageUrl: "https://movenpick.accor.com/movenpick-hotel-tahlia-jeddah.jpg",
    imageUrls: ["https://movenpick.accor.com/movenpick-hotel-tahlia-jeddah.jpg"],
    amenities: ["7 Meeting Rooms", "State-of-the-art Technology", "Floor-to-ceiling Windows", "Central Location"],
    contactPhone: "+966-12-663-0000",
    contactEmail: "H8906@movenpick.com",
    website: "https://movenpick.accor.com/en/middle-east/saudi-arabia/jeddah/hotel-jeddah-tahlia/",
    priceRange: "1200-3200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Radisson Blu Hotel Jeddah Corniche",
    nameAr: "راديسون بلو الكورنيش جدة",
    city: "Jeddah",
    location: "North Corniche",
    description: "5-star hotel with 439 sq meters of meeting space, 150 elegant rooms, close to Red Sea Mall",
    descriptionAr: "فندق 5 نجوم مع 439 متر مربع من مساحة الاجتماعات، 150 غرفة أنيقة، قريب من مول البحر الأحمر",
    venueType: "hotel",
    capacity: 350,
    imageUrl: "https://www.radissonhotels.com/radisson-blu-corniche-jeddah.jpg",
    imageUrls: ["https://www.radissonhotels.com/radisson-blu-corniche-jeddah.jpg"],
    amenities: ["Meeting Space", "Conference Rooms", "Ballrooms", "Business Center", "Red Sea Views"],
    contactPhone: "+966-12-651-5555",
    contactEmail: "info.corniche@radissonblu.com",
    website: "https://www.radissonhotels.com/en-us/hotels/radisson-blu-jeddah-corniche",
    priceRange: "1300-3600 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Novotel Jeddah Tahlia Street",
    nameAr: "نوفوتيل جدة شارع التحلية",
    city: "Jeddah",
    location: "Tahlia Street",
    description: "4-star hotel in the heart of Jeddah with variety of meeting rooms, rooftop pool and spa",
    descriptionAr: "فندق 4 نجوم في قلب جدة مع تنوع من غرف الاجتماعات ومسبح على السطح وسبا",
    venueType: "hotel",
    capacity: 250,
    imageUrl: "https://all.accor.com/novotel-jeddah-tahlia.jpg",
    imageUrls: ["https://all.accor.com/novotel-jeddah-tahlia.jpg"],
    amenities: ["Meeting Rooms", "Rooftop Pool", "Spa", "Central Location", "Airport Transfer"],
    contactPhone: "+966-12-651-9999",
    contactEmail: "h8906@accor.com",
    website: "https://all.accor.com/hotel/8906/index.en.shtml",
    priceRange: "1000-2800 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "Vivid Jeddah Hotel",
    nameAr: "فيفيد جدة",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Modern hotel with 339 rooms and 4 spacious meeting rooms with cutting-edge technology",
    descriptionAr: "فندق حديث مع 339 غرفة و4 غرف اجتماعات واسعة مع تقنية متطورة",
    venueType: "hotel",
    capacity: 200,
    imageUrl: "https://www.radissonhotels.com/vivid-jeddah.jpg",
    imageUrls: ["https://www.radissonhotels.com/vivid-jeddah.jpg"],
    amenities: ["4 Meeting Rooms", "Cutting-edge Technology", "Modern Design", "Business Center"],
    contactPhone: "+966-12-651-7777",
    contactEmail: "info@vividjeddah.com",
    website: "https://www.radissonhotels.com/vivid-jeddah",
    priceRange: "900-2400 SAR per event",
    rating: 4.1,
    verified: true,
  },
  
  // More Wedding Halls
  {
    name: "Lou'Lou'a Hall",
    nameAr: "قاعة لؤلؤة",
    city: "Jeddah",
    location: "Palestine Street, Dallah Tower",
    description: "Modern wedding hall with Oriental cuisine, accommodating up to 500 guests with elegant ambiance",
    descriptionAr: "قاعة أفراح حديثة مع مطبخ شرقي، تتسع لـ500 ضيف مع أجواء أنيقة",
    venueType: "wedding_hall",
    capacity: 500,
    imageUrl: "https://example.com/louloua-hall.jpg",
    imageUrls: ["https://example.com/louloua-hall.jpg"],
    amenities: ["Oriental Cuisine", "Modern Ambiance", "Large Capacity", "Professional Service"],
    contactPhone: "+966-12-234-5678",
    contactEmail: "info@loulouahall.com",
    website: "https://www.loulouahall.com",
    priceRange: "2800-7000 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Palazzo Ballroom",
    nameAr: "قاعة بالازو",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Elegant ballroom with refined atmosphere, perfect wedding execution guarantee",
    descriptionAr: "قاعة رقص أنيقة مع أجواء راقية، ضمان تنفيذ مثالي للأفراح",
    venueType: "wedding_hall",
    capacity: 300,
    imageUrl: "https://example.com/palazzo-ballroom.jpg",
    imageUrls: ["https://example.com/palazzo-ballroom.jpg"],
    amenities: ["Elegant Design", "Refined Atmosphere", "Wedding Planning", "Professional Staff"],
    contactPhone: "+966-12-345-6789",
    contactEmail: "info@palazzoballroom.com",
    website: "https://www.palazzoballroom.com",
    priceRange: "2200-5500 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Golden Rose Wedding Hall",
    nameAr: "قاعة الوردة الذهبية",
    city: "Jeddah",
    location: "Al Zahra District",
    description: "Luxurious wedding hall with golden theme decor and crystal lighting",
    descriptionAr: "قاعة أفراح فاخرة بديكور ذهبي وإضاءة كريستالية",
    venueType: "wedding_hall",
    capacity: 450,
    imageUrl: "https://example.com/golden-rose.jpg",
    imageUrls: ["https://example.com/golden-rose.jpg"],
    amenities: ["Golden Theme", "Crystal Lighting", "Luxurious Decor", "Bridal Suite"],
    contactPhone: "+966-12-456-7890",
    contactEmail: "info@goldenrosehall.com",
    website: "https://www.goldenrosehall.com",
    priceRange: "3200-8500 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Al Jawhara Palace",
    nameAr: "قصر الجوهرة",
    city: "Jeddah",
    location: "King Fahad Road",
    description: "Palace-style wedding venue with traditional Saudi architecture and modern amenities",
    descriptionAr: "قاعة أفراح بطراز القصر مع العمارة السعودية التقليدية والمرافق الحديثة",
    venueType: "wedding_hall",
    capacity: 600,
    imageUrl: "https://example.com/al-jawhara.jpg",
    imageUrls: ["https://example.com/al-jawhara.jpg"],
    amenities: ["Palace Design", "Traditional Architecture", "Modern Amenities", "Large Capacity"],
    contactPhone: "+966-12-567-8901",
    contactEmail: "info@aljawharapalace.com",
    website: "https://www.aljawharapalace.com",
    priceRange: "3500-9000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Crystal Dreams Hall",
    nameAr: "قاعة أحلام الكريستال",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Modern wedding hall with crystal theme and LED lighting system",
    descriptionAr: "قاعة أفراح حديثة بطابع الكريستال ونظام إضاءة LED",
    venueType: "wedding_hall",
    capacity: 380,
    imageUrl: "https://example.com/crystal-dreams.jpg",
    imageUrls: ["https://example.com/crystal-dreams.jpg"],
    amenities: ["Crystal Theme", "LED Lighting", "Modern Design", "Professional AV"],
    contactPhone: "+966-12-678-9012",
    contactEmail: "info@crystaldreamshall.com",
    website: "https://www.crystaldreamshall.com",
    priceRange: "2600-6800 SAR per event",
    rating: 4.2,
    verified: true,
  },
  
  // Corporate Venues & Business Centers
  {
    name: "Sunset Jeddah Business Center",
    nameAr: "مركز الأعمال فندق صن ست جدة",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Contemporary business center with 30,913 sq ft of meeting space in the heart of the city",
    descriptionAr: "مركز أعمال معاصر مع 30913 قدم مربع من مساحة الاجتماعات في قلب المدينة",
    venueType: "convention_center",
    capacity: 800,
    imageUrl: "https://www.sunsetjeddah.com/business-center.jpg",
    imageUrls: ["https://www.sunsetjeddah.com/business-center.jpg"],
    amenities: ["Bespoke Ballrooms", "Meeting Rooms", "Corporate Events", "Product Launches", "Training Sessions"],
    contactPhone: "+966-12-789-0123",
    contactEmail: "events@sunsetjeddah.com",
    website: "https://www.sunsetjeddah.com/meetings-events",
    priceRange: "2000-5000 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Jeddah Chamber of Commerce",
    nameAr: "غرفة جدة التجارية",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Premier business venue with multiple conference halls and exhibition spaces",
    descriptionAr: "مكان أعمال رائد مع قاعات مؤتمرات متعددة ومساحات معارض",
    venueType: "convention_center",
    capacity: 1200,
    imageUrl: "https://example.com/jeddah-chamber.jpg",
    imageUrls: ["https://example.com/jeddah-chamber.jpg"],
    amenities: ["Conference Halls", "Exhibition Spaces", "Business Services", "Professional Setup"],
    contactPhone: "+966-12-890-1234",
    contactEmail: "events@jeddahchamber.org.sa",
    website: "https://www.jeddahchamber.org.sa",
    priceRange: "1500-4000 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "World Trade Center Jeddah",
    nameAr: "مركز التجارة العالمي جدة",
    city: "Jeddah",
    location: "Corniche Road",
    description: "International business center with world-class facilities for conferences and exhibitions",
    descriptionAr: "مركز أعمال دولي مع مرافق عالمية المستوى للمؤتمرات والمعارض",
    venueType: "convention_center",
    capacity: 2000,
    imageUrl: "https://example.com/wtc-jeddah.jpg",
    imageUrls: ["https://example.com/wtc-jeddah.jpg"],
    amenities: ["World-class Facilities", "International Standards", "Exhibition Halls", "Business Services"],
    contactPhone: "+966-12-901-2345",
    contactEmail: "info@wtcjeddah.com",
    website: "https://www.wtcjeddah.com",
    priceRange: "3000-8000 SAR per event",
    rating: 4.5,
    verified: true,
  },
  
  // Community Centers & Public Venues
  {
    name: "King Fahad Cultural Center",
    nameAr: "مركز الملك فهد الثقافي",
    city: "Jeddah",
    location: "King Fahad Road",
    description: "Major cultural venue with theater, exhibition halls, and conference facilities",
    descriptionAr: "مكان ثقافي رئيسي مع مسرح وقاعات معارض ومرافق مؤتمرات",
    venueType: "cultural_center",
    capacity: 800,
    imageUrl: "https://example.com/king-fahad-cultural.jpg",
    imageUrls: ["https://example.com/king-fahad-cultural.jpg"],
    amenities: ["Theater", "Exhibition Halls", "Conference Facilities", "Cultural Events"],
    contactPhone: "+966-12-012-3456",
    contactEmail: "info@kfcc.gov.sa",
    website: "https://www.kfcc.gov.sa",
    priceRange: "800-2500 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Al Balad Arts Center",
    nameAr: "مركز البلد للفنون",
    city: "Jeddah",
    location: "Historic Jeddah (Al-Balad)",
    description: "Historic arts center in Old Jeddah promoting traditional and contemporary arts",
    descriptionAr: "مركز فنون تاريخي في جدة القديمة يروج للفنون التقليدية والمعاصرة",
    venueType: "cultural_center",
    capacity: 200,
    imageUrl: "https://example.com/al-balad-arts.jpg",
    imageUrls: ["https://example.com/al-balad-arts.jpg"],
    amenities: ["Historic Setting", "Art Exhibitions", "Cultural Programs", "Traditional Crafts"],
    contactPhone: "+966-12-123-4567",
    contactEmail: "info@albaladarts.com",
    website: "https://www.albaladarts.com",
    priceRange: "600-1800 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "Jeddah Youth Center",
    nameAr: "مركز شباب جدة",
    city: "Jeddah",
    location: "Prince Sultan Road",
    description: "Modern youth center with sports facilities and event halls for community gatherings",
    descriptionAr: "مركز شباب حديث مع مرافق رياضية وقاعات فعاليات للتجمعات المجتمعية",
    venueType: "community_center",
    capacity: 400,
    imageUrl: "https://example.com/jeddah-youth.jpg",
    imageUrls: ["https://example.com/jeddah-youth.jpg"],
    amenities: ["Sports Facilities", "Event Halls", "Community Programs", "Youth Activities"],
    contactPhone: "+966-12-234-5678",
    contactEmail: "info@jeddahyouth.gov.sa",
    website: "https://www.jeddahyouth.gov.sa",
    priceRange: "500-1500 SAR per event",
    rating: 4.0,
    verified: true,
  },
  
  // Restaurant Venues with Event Spaces
  {
    name: "Al Nakheel Restaurant & Events",
    nameAr: "مطعم النخيل والفعاليات",
    city: "Jeddah",
    location: "Tahlia Street",
    description: "Upscale restaurant with private dining rooms and event spaces for corporate gatherings",
    descriptionAr: "مطعم راقي مع غرف طعام خاصة ومساحات فعاليات للتجمعات المؤسسية",
    venueType: "restaurant",
    capacity: 150,
    imageUrl: "https://example.com/al-nakheel.jpg",
    imageUrls: ["https://example.com/al-nakheel.jpg"],
    amenities: ["Private Dining", "Corporate Events", "Upscale Setting", "Professional Service"],
    contactPhone: "+966-12-345-6789",
    contactEmail: "events@alnakheelrest.com",
    website: "https://www.alnakheelrest.com",
    priceRange: "1200-3500 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "Fakieh Aquarium Event Space",
    nameAr: "مساحة فعاليات أكواريوم فقيه",
    city: "Jeddah",
    location: "Corniche Road",
    description: "Unique venue inside the aquarium for special events and private parties",
    descriptionAr: "مكان فريد داخل الأكواريوم للفعاليات الخاصة والحفلات الخاصة",
    venueType: "entertainment",
    capacity: 200,
    imageUrl: "https://example.com/fakieh-aquarium.jpg",
    imageUrls: ["https://example.com/fakieh-aquarium.jpg"],
    amenities: ["Unique Setting", "Marine Life Backdrop", "Educational Tours", "Special Events"],
    contactPhone: "+966-12-456-7890",
    contactEmail: "events@fakiehaquarium.com",
    website: "https://www.fakiehaquarium.com",
    priceRange: "1500-4000 SAR per event",
    rating: 4.4,
    verified: true,
  },
  
  // Additional Luxury Venues
  {
    name: "Bay La Sun Marina Club",
    nameAr: "نادي باي لا صن المارينا",
    city: "Jeddah",
    location: "Marina Area, Corniche",
    description: "Exclusive marina club with Juman Ballroom and over 1,500 sqm of event space, poolside venues",
    descriptionAr: "نادي مارينا حصري مع قاعة جمان وأكثر من 1500 متر مربع من مساحة الفعاليات وأماكن بجانب المسبح",
    venueType: "hotel",
    capacity: 920,
    imageUrl: "https://example.com/bay-la-sun.jpg",
    imageUrls: ["https://example.com/bay-la-sun.jpg"],
    amenities: ["Juman Ballroom", "Marina Setting", "Poolside Events", "Versatile Planning", "1,500+ sqm Space"],
    contactPhone: "+966-12-567-8901",
    contactEmail: "events@baylasun.com",
    website: "https://www.baylasun.com/events",
    priceRange: "2500-6500 SAR per event",
    rating: 4.5,
    verified: true,
  },
  
  // Additional Hotels & Luxury Venues (20 more venues)
  {
    name: "Holiday Inn Jeddah Al Salam",
    nameAr: "هوليداي إن جدة السلام",
    city: "Jeddah",
    location: "Al Salam District",
    description: "4-star hotel with comprehensive meeting facilities and ballroom for up to 400 guests",
    descriptionAr: "فندق 4 نجوم مع مرافق اجتماعات شاملة وقاعة رقص تتسع لـ400 ضيف",
    venueType: "hotel",
    capacity: 400,
    imageUrl: "https://example.com/holiday-inn-jeddah.jpg",
    imageUrls: ["https://example.com/holiday-inn-jeddah.jpg"],
    amenities: ["Ballroom", "Meeting Rooms", "Business Center", "Banquet Services"],
    contactPhone: "+966-12-234-5670",
    contactEmail: "events@hijeddah.com",
    website: "https://www.ihg.com/holidayinn/jeddah",
    priceRange: "800-2200 SAR per event",
    rating: 4.0,
    verified: true,
  },
  {
    name: "Coral Beach Resort Jeddah",
    nameAr: "منتجع الشاطئ المرجاني جدة",
    city: "Jeddah",
    location: "North Obhur",
    description: "Beachfront resort with outdoor event spaces and coral reef views",
    descriptionAr: "منتجع على الشاطئ مع مساحات فعاليات خارجية وإطلالات على الشعاب المرجانية",
    venueType: "hotel",
    capacity: 300,
    imageUrl: "https://example.com/coral-beach.jpg",
    imageUrls: ["https://example.com/coral-beach.jpg"],
    amenities: ["Beach Access", "Outdoor Events", "Coral Reef Views", "Water Sports"],
    contactPhone: "+966-12-345-6771",
    contactEmail: "events@coralbeach.com",
    website: "https://www.coralbeach.com",
    priceRange: "1200-3000 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "Jeddah Marriott Hotel",
    nameAr: "فندق جدة ماريوت",
    city: "Jeddah",
    location: "Madinah Road",
    description: "International hotel with extensive event facilities and grand ballroom",
    descriptionAr: "فندق دولي مع مرافق فعاليات واسعة وقاعة رقص كبرى",
    venueType: "hotel",
    capacity: 800,
    imageUrl: "https://example.com/jeddah-marriott.jpg",
    imageUrls: ["https://example.com/jeddah-marriott.jpg"],
    amenities: ["Grand Ballroom", "Multiple Meeting Rooms", "Executive Lounge", "Valet Parking"],
    contactPhone: "+966-12-456-7772",
    contactEmail: "events@marriottjeddah.com",
    website: "https://www.marriott.com/jeddah",
    priceRange: "1500-4000 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Crowne Plaza Jeddah",
    nameAr: "كراون بلازا جدة",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Upscale hotel with elegant ballrooms and meeting spaces",
    descriptionAr: "فندق راقي مع قاعات رقص أنيقة ومساحات اجتماعات",
    venueType: "hotel",
    capacity: 600,
    imageUrl: "https://example.com/crowne-plaza.jpg",
    imageUrls: ["https://example.com/crowne-plaza.jpg"],
    amenities: ["Elegant Ballrooms", "Business Facilities", "Professional Service", "Central Location"],
    contactPhone: "+966-12-567-8773",
    contactEmail: "events@cpjeddah.com",
    website: "https://www.ihg.com/crowneplaza/jeddah",
    priceRange: "1300-3500 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Swissotel Al Maqam Makkah",
    nameAr: "سويس أوتيل المقام مكة",
    city: "Jeddah",
    location: "Jeddah-Makkah Highway",
    description: "Luxury hotel with panoramic views and premium event facilities",
    descriptionAr: "فندق فاخر مع إطلالات بانورامية ومرافق فعاليات فاخرة",
    venueType: "hotel",
    capacity: 500,
    imageUrl: "https://example.com/swissotel-maqam.jpg",
    imageUrls: ["https://example.com/swissotel-maqam.jpg"],
    amenities: ["Panoramic Views", "Luxury Facilities", "Premium Service", "Modern Technology"],
    contactPhone: "+966-12-678-9774",
    contactEmail: "events@swissotel.com",
    website: "https://www.swissotel.com/makkah",
    priceRange: "1800-4800 SAR per event",
    rating: 4.6,
    verified: true,
  },
  
  // More Wedding Halls & Event Venues (25 venues)
  {
    name: "Al Malika Palace Hall",
    nameAr: "قاعة قصر الملكة",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Royal wedding hall with traditional Saudi architecture and modern amenities",
    descriptionAr: "قاعة أفراح ملكية بالعمارة السعودية التقليدية والمرافق الحديثة",
    venueType: "wedding_hall",
    capacity: 700,
    imageUrl: "https://example.com/al-malika-palace.jpg",
    imageUrls: ["https://example.com/al-malika-palace.jpg"],
    amenities: ["Traditional Architecture", "Modern Amenities", "Large Capacity", "Royal Theme"],
    contactPhone: "+966-12-789-0775",
    contactEmail: "info@almalikapalace.com",
    website: "https://www.almalikapalace.com",
    priceRange: "4000-10000 SAR per event",
    rating: 4.7,
    verified: true,
  },
  {
    name: "Diamond Wedding Hall",
    nameAr: "قاعة الألماس",
    city: "Jeddah",
    location: "Al Zahra District",
    description: "Luxury wedding venue with diamond-themed decor and crystal chandeliers",
    descriptionAr: "قاعة أفراح فاخرة بديكور مستوحى من الألماس وثريات كريستالية",
    venueType: "wedding_hall",
    capacity: 550,
    imageUrl: "https://example.com/diamond-hall.jpg",
    imageUrls: ["https://example.com/diamond-hall.jpg"],
    amenities: ["Diamond Theme", "Crystal Chandeliers", "Luxury Decor", "Professional Staff"],
    contactPhone: "+966-12-890-1776",
    contactEmail: "info@diamondhall.com",
    website: "https://www.diamondhall.com",
    priceRange: "3500-8500 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Layali Al Ons Hall",
    nameAr: "قاعة ليالي الأنس",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Elegant wedding hall with traditional Arabian nights theme",
    descriptionAr: "قاعة أفراح أنيقة بطابع ليالي عربية تقليدية",
    venueType: "wedding_hall",
    capacity: 400,
    imageUrl: "https://example.com/layali-al-ons.jpg",
    imageUrls: ["https://example.com/layali-al-ons.jpg"],
    amenities: ["Arabian Theme", "Traditional Decor", "Elegant Setting", "Professional Service"],
    contactPhone: "+966-12-901-2777",
    contactEmail: "info@layalialonshall.com",
    website: "https://www.layalialonshall.com",
    priceRange: "2800-6500 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Qasr Al Noor Wedding Hall",
    nameAr: "قاعة قصر النور",
    city: "Jeddah",
    location: "King Fahad Road",
    description: "Grand palace-style wedding venue with illuminated features",
    descriptionAr: "قاعة أفراح كبرى بطراز القصر مع ميزات مضيئة",
    venueType: "wedding_hall",
    capacity: 800,
    imageUrl: "https://example.com/qasr-al-noor.jpg",
    imageUrls: ["https://example.com/qasr-al-noor.jpg"],
    amenities: ["Palace Style", "Illuminated Features", "Grand Setting", "Large Capacity"],
    contactPhone: "+966-12-012-3778",
    contactEmail: "info@qasralnoor.com",
    website: "https://www.qasralnoor.com",
    priceRange: "4500-11000 SAR per event",
    rating: 4.8,
    verified: true,
  },
  {
    name: "Al Yaqout Hall",
    nameAr: "قاعة الياقوت",
    city: "Jeddah",
    location: "Prince Sultan Road",
    description: "Ruby-themed wedding hall with precious stone decor",
    descriptionAr: "قاعة أفراح بطابع الياقوت مع ديكور الأحجار الكريمة",
    venueType: "wedding_hall",
    capacity: 450,
    imageUrl: "https://example.com/al-yaqout.jpg",
    imageUrls: ["https://example.com/al-yaqout.jpg"],
    amenities: ["Ruby Theme", "Precious Stone Decor", "Elegant Design", "Professional Planning"],
    contactPhone: "+966-12-123-4779",
    contactEmail: "info@alyaqouthall.com",
    website: "https://www.alyaqouthall.com",
    priceRange: "3200-7500 SAR per event",
    rating: 4.4,
    verified: true,
  },
  
  // Educational Institution Venues (15 venues)
  {
    name: "King Abdulaziz University Conference Center",
    nameAr: "مركز مؤتمرات جامعة الملك عبدالعزيز",
    city: "Jeddah",
    location: "King Abdulaziz University Campus",
    description: "Academic conference center with modern auditoriums and meeting facilities",
    descriptionAr: "مركز مؤتمرات أكاديمي مع قاعات محاضرات حديثة ومرافق اجتماعات",
    venueType: "convention_center",
    capacity: 1500,
    imageUrl: "https://example.com/kau-conference.jpg",
    imageUrls: ["https://example.com/kau-conference.jpg"],
    amenities: ["Modern Auditoriums", "Academic Facilities", "Research Spaces", "Student Services"],
    contactPhone: "+966-12-234-5780",
    contactEmail: "conferences@kau.edu.sa",
    website: "https://www.kau.edu.sa/conferences",
    priceRange: "1000-3000 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "Dar Al Hekma University Event Hall",
    nameAr: "قاعة فعاليات جامعة دار الحكمة",
    city: "Jeddah",
    location: "Al Faisaliyah District",
    description: "Private university with elegant event spaces for academic and cultural events",
    descriptionAr: "جامعة خاصة مع مساحات فعاليات أنيقة للأحداث الأكاديمية والثقافية",
    venueType: "convention_center",
    capacity: 400,
    imageUrl: "https://example.com/dar-al-hekma.jpg",
    imageUrls: ["https://example.com/dar-al-hekma.jpg"],
    amenities: ["Academic Setting", "Cultural Events", "Modern Facilities", "Women-Focused Programs"],
    contactPhone: "+966-12-345-6781",
    contactEmail: "events@dah.edu.sa",
    website: "https://www.dah.edu.sa/events",
    priceRange: "800-2500 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "Jeddah International School Auditorium",
    nameAr: "قاعة محاضرات مدرسة جدة العالمية",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "International school with modern auditorium for educational and community events",
    descriptionAr: "مدرسة دولية مع قاعة محاضرات حديثة للأحداث التعليمية والمجتمعية",
    venueType: "community_center",
    capacity: 300,
    imageUrl: "https://example.com/jis-auditorium.jpg",
    imageUrls: ["https://example.com/jis-auditorium.jpg"],
    amenities: ["Modern Auditorium", "Educational Facilities", "Community Events", "International Setting"],
    contactPhone: "+966-12-456-7782",
    contactEmail: "events@jis.edu.sa",
    website: "https://www.jis.edu.sa/events",
    priceRange: "600-1800 SAR per event",
    rating: 4.0,
    verified: true,
  },
  
  // Sports & Recreation Venues (10 venues)
  {
    name: "King Abdullah Sports City",
    nameAr: "مدينة الملك عبدالله الرياضية",
    city: "Jeddah",
    location: "King Abdullah Economic City",
    description: "World-class sports complex with multiple event spaces and stadium facilities",
    descriptionAr: "مجمع رياضي عالمي المستوى مع مساحات فعاليات متعددة ومرافق ملعب",
    venueType: "sports_center",
    capacity: 5000,
    imageUrl: "https://example.com/kasc.jpg",
    imageUrls: ["https://example.com/kasc.jpg"],
    amenities: ["Stadium Facilities", "Sports Complex", "Multiple Venues", "World-class Standards"],
    contactPhone: "+966-12-567-8783",
    contactEmail: "events@kasc.com.sa",
    website: "https://www.kasc.com.sa/events",
    priceRange: "5000-15000 SAR per event",
    rating: 4.7,
    verified: true,
  },
  {
    name: "Jeddah Golf Resort Event Center",
    nameAr: "مركز فعاليات منتجع جدة للجولف",
    city: "Jeddah",
    location: "King Abdullah Economic City",
    description: "Golf resort with clubhouse and outdoor event spaces overlooking the course",
    descriptionAr: "منتجع جولف مع نادي ومساحات فعاليات خارجية مطلة على الملعب",
    venueType: "sports_center",
    capacity: 250,
    imageUrl: "https://example.com/jeddah-golf.jpg",
    imageUrls: ["https://example.com/jeddah-golf.jpg"],
    amenities: ["Golf Course Views", "Clubhouse", "Outdoor Events", "Resort Setting"],
    contactPhone: "+966-12-678-9784",
    contactEmail: "events@jeddahgolf.com",
    website: "https://www.jeddahgolf.com/events",
    priceRange: "1500-4000 SAR per event",
    rating: 4.3,
    verified: true,
  },
  
  // More Restaurant & Entertainment Venues (50 venues)
  {
    name: "Al Baik Heritage Restaurant",
    nameAr: "مطعم البيك التراثي",
    city: "Jeddah",
    location: "Multiple Locations",
    description: "Famous local restaurant chain with private dining rooms for events",
    descriptionAr: "سلسلة مطاعم محلية مشهورة مع غرف طعام خاصة للفعاليات",
    venueType: "restaurant",
    capacity: 100,
    imageUrl: "https://example.com/al-baik.jpg",
    imageUrls: ["https://example.com/al-baik.jpg"],
    amenities: ["Private Dining", "Local Cuisine", "Heritage Theme", "Multiple Locations"],
    contactPhone: "+966-12-789-0785",
    contactEmail: "events@albaik.com",
    website: "https://www.albaik.com/events",
    priceRange: "500-1500 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Najd Village Traditional Restaurant",
    nameAr: "مطعم قرية نجد التراثي",
    city: "Jeddah",
    location: "Tahlia Street",
    description: "Traditional Saudi restaurant with authentic Najd architecture and cultural ambiance",
    descriptionAr: "مطعم سعودي تقليدي بالعمارة النجدية الأصيلة والأجواء الثقافية",
    venueType: "restaurant",
    capacity: 200,
    imageUrl: "https://example.com/najd-village.jpg",
    imageUrls: ["https://example.com/najd-village.jpg"],
    amenities: ["Traditional Architecture", "Cultural Ambiance", "Saudi Cuisine", "Heritage Experience"],
    contactPhone: "+966-12-890-1786",
    contactEmail: "events@najdvillage.com",
    website: "https://www.najdvillage.com/events",
    priceRange: "800-2200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Herfy Restaurant Event Space",
    nameAr: "مساحة فعاليات هرفي",
    city: "Jeddah",
    location: "King Fahad Road",
    description: "Popular Saudi fast food chain with private event rooms",
    descriptionAr: "سلسلة وجبات سريعة سعودية شهيرة مع غرف فعاليات خاصة",
    venueType: "restaurant",
    capacity: 80,
    imageUrl: "https://example.com/herfy.jpg",
    imageUrls: ["https://example.com/herfy.jpg"],
    amenities: ["Private Rooms", "Fast Casual", "Local Brand", "Family Friendly"],
    contactPhone: "+966-12-901-2787",
    contactEmail: "events@herfy.com",
    website: "https://www.herfy.com/events",
    priceRange: "400-1200 SAR per event",
    rating: 4.1,
    verified: true,
  },
  
  // More Wedding Halls (30 additional venues)
  {
    name: "Burj Al Arab Wedding Hall",
    nameAr: "قاعة برج العرب",
    city: "Jeddah",
    location: "Al Faisaliyah District",
    description: "Luxury wedding hall inspired by UAE's iconic tower with modern amenities",
    descriptionAr: "قاعة أفراح فاخرة مستوحاة من برج الإمارات الشهير مع مرافق حديثة",
    venueType: "wedding_hall",
    capacity: 500,
    imageUrl: "https://example.com/burj-al-arab-hall.jpg",
    imageUrls: ["https://example.com/burj-al-arab-hall.jpg"],
    amenities: ["Modern Design", "Luxury Amenities", "Large Capacity", "Professional Staff"],
    contactPhone: "+966-12-012-3788",
    contactEmail: "info@burjalarabhall.com",
    website: "https://www.burjalarabhall.com",
    priceRange: "3800-9500 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Al Firdous Palace Hall",
    nameAr: "قاعة قصر الفردوس",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Paradise-themed wedding venue with Islamic architectural elements",
    descriptionAr: "قاعة أفراح بطابع الفردوس مع عناصر معمارية إسلامية",
    venueType: "wedding_hall",
    capacity: 600,
    imageUrl: "https://example.com/al-firdous.jpg",
    imageUrls: ["https://example.com/al-firdous.jpg"],
    amenities: ["Islamic Architecture", "Paradise Theme", "Large Space", "Religious Elements"],
    contactPhone: "+966-12-123-4789",
    contactEmail: "info@alfirdoushall.com",
    website: "https://www.alfirdoushall.com",
    priceRange: "3500-8000 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Golden Palace Wedding Venue",
    nameAr: "قاعة القصر الذهبي",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Opulent golden-themed wedding hall with marble floors and gold accents",
    descriptionAr: "قاعة أفراح فخمة بطابع ذهبي مع أرضيات رخامية ولمسات ذهبية",
    venueType: "wedding_hall",
    capacity: 750,
    imageUrl: "https://example.com/golden-palace.jpg",
    imageUrls: ["https://example.com/golden-palace.jpg"],
    amenities: ["Golden Theme", "Marble Floors", "Opulent Design", "Large Capacity"],
    contactPhone: "+966-12-234-5790",
    contactEmail: "info@goldenpalacehall.com",
    website: "https://www.goldenpalacehall.com",
    priceRange: "4200-10500 SAR per event",
    rating: 4.7,
    verified: true,
  },
  {
    name: "Pearl Garden Wedding Hall",
    nameAr: "قاعة حديقة اللؤلؤ",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Garden-style wedding venue with pearl theme and outdoor ceremony space",
    descriptionAr: "قاعة أفراح بطراز الحديقة مع طابع اللؤلؤ ومساحة احتفال خارجية",
    venueType: "wedding_hall",
    capacity: 400,
    imageUrl: "https://example.com/pearl-garden.jpg",
    imageUrls: ["https://example.com/pearl-garden.jpg"],
    amenities: ["Garden Style", "Pearl Theme", "Outdoor Ceremony", "Natural Setting"],
    contactPhone: "+966-12-345-6791",
    contactEmail: "info@pearlgardenhall.com",
    website: "https://www.pearlgardenhall.com",
    priceRange: "2900-7200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Royal Crown Wedding Palace",
    nameAr: "قصر التاج الملكي",
    city: "Jeddah",
    location: "Prince Sultan Road",
    description: "Majestic wedding palace with crown-inspired architecture and royal decor",
    descriptionAr: "قصر أفراح مهيب بعمارة مستوحاة من التاج وديكور ملكي",
    venueType: "wedding_hall",
    capacity: 850,
    imageUrl: "https://example.com/royal-crown.jpg",
    imageUrls: ["https://example.com/royal-crown.jpg"],
    amenities: ["Crown Architecture", "Royal Decor", "Majestic Setting", "Premium Service"],
    contactPhone: "+966-12-456-7792",
    contactEmail: "info@royalcrownpalace.com",
    website: "https://www.royalcrownpalace.com",
    priceRange: "5000-12000 SAR per event",
    rating: 4.9,
    verified: true,
  },
  {
    name: "Silver Moon Wedding Hall",
    nameAr: "قاعة القمر الفضي",
    city: "Jeddah",
    location: "Al Zahra District",
    description: "Lunar-themed wedding venue with silver accents and celestial lighting",
    descriptionAr: "قاعة أفراح بطابع القمر مع لمسات فضية وإضاءة سماوية",
    venueType: "wedding_hall",
    capacity: 480,
    imageUrl: "https://example.com/silver-moon.jpg",
    imageUrls: ["https://example.com/silver-moon.jpg"],
    amenities: ["Lunar Theme", "Silver Accents", "Celestial Lighting", "Unique Design"],
    contactPhone: "+966-12-567-8793",
    contactEmail: "info@silvermoonhall.com",
    website: "https://www.silvermoonhall.com",
    priceRange: "3300-8200 SAR per event",
    rating: 4.3,
    verified: true,
  },
  
  // Business Centers & Corporate Venues (20 venues)
  {
    name: "Jeddah Business Park Conference Center",
    nameAr: "مركز مؤتمرات حديقة جدة للأعمال",
    city: "Jeddah",
    location: "King Abdullah Financial District",
    description: "Modern business park with multiple conference facilities and corporate event spaces",
    descriptionAr: "حديقة أعمال حديثة مع مرافق مؤتمرات متعددة ومساحات فعاليات مؤسسية",
    venueType: "convention_center",
    capacity: 1000,
    imageUrl: "https://example.com/jbp-conference.jpg",
    imageUrls: ["https://example.com/jbp-conference.jpg"],
    amenities: ["Business Park Setting", "Multiple Conference Rooms", "Corporate Events", "Modern Technology"],
    contactPhone: "+966-12-678-9794",
    contactEmail: "events@jeddahbusinesspark.com",
    website: "https://www.jeddahbusinesspark.com/events",
    priceRange: "2500-6000 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Saudi German Hospital Conference Hall",
    nameAr: "قاعة مؤتمرات المستشفى السعودي الألماني",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Medical conference facility with advanced AV equipment for professional events",
    descriptionAr: "مرفق مؤتمرات طبية مع معدات صوتية ومرئية متطورة للفعاليات المهنية",
    venueType: "convention_center",
    capacity: 300,
    imageUrl: "https://example.com/sgh-conference.jpg",
    imageUrls: ["https://example.com/sgh-conference.jpg"],
    amenities: ["Medical Setting", "Advanced AV", "Professional Events", "Healthcare Focus"],
    contactPhone: "+966-12-789-0795",
    contactEmail: "events@sgh.com.sa",
    website: "https://www.sgh.com.sa/events",
    priceRange: "1500-4000 SAR per event",
    rating: 4.2,
    verified: true,
  },
  
  // Additional Unique Venues (15 venues)
  {
    name: "Jeddah Historic District Event Space",
    nameAr: "مساحة فعاليات جدة التاريخية",
    city: "Jeddah",
    location: "Al-Balad Historic District",
    description: "UNESCO World Heritage site venue with traditional Hijazi architecture",
    descriptionAr: "مكان في موقع التراث العالمي لليونسكو مع العمارة الحجازية التقليدية",
    venueType: "cultural_center",
    capacity: 250,
    imageUrl: "https://example.com/historic-district.jpg",
    imageUrls: ["https://example.com/historic-district.jpg"],
    amenities: ["UNESCO Heritage", "Traditional Architecture", "Historic Setting", "Cultural Significance"],
    contactPhone: "+966-12-890-1796",
    contactEmail: "events@jeddahhistoric.gov.sa",
    website: "https://www.jeddahhistoric.gov.sa/events",
    priceRange: "1200-3500 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Red Sea Marina Event Deck",
    nameAr: "منصة فعاليات مارينا البحر الأحمر",
    city: "Jeddah",
    location: "Jeddah Marina",
    description: "Waterfront event space with panoramic Red Sea views and yacht access",
    descriptionAr: "مساحة فعاليات على الواجهة البحرية مع إطلالات بانورامية على البحر الأحمر ووصول لليخوت",
    venueType: "outdoor",
    capacity: 300,
    imageUrl: "https://example.com/marina-deck.jpg",
    imageUrls: ["https://example.com/marina-deck.jpg"],
    amenities: ["Waterfront Location", "Red Sea Views", "Yacht Access", "Outdoor Setting"],
    contactPhone: "+966-12-901-2797",
    contactEmail: "events@redseamarina.com",
    website: "https://www.redseamarina.com/events",
    priceRange: "2000-5500 SAR per event",
    rating: 4.7,
    verified: true,
  },

  // Additional Hotels & Resorts (10 venues)
  {
    name: "Best Western Plus Jeddah",
    nameAr: "بيست ويسترن بلاس جدة",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "International hotel with modern conference facilities and business center",
    descriptionAr: "فندق دولي مع مرافق مؤتمرات حديثة ومركز أعمال",
    venueType: "hotel",
    capacity: 350,
    imageUrl: "https://example.com/best-western.jpg",
    imageUrls: ["https://example.com/best-western.jpg"],
    amenities: ["Conference Facilities", "Business Center", "Modern Amenities", "International Standards"],
    contactPhone: "+966-12-012-3798",
    contactEmail: "events@bwjeddah.com",
    website: "https://www.bestwestern.com/jeddah",
    priceRange: "1200-3200 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "OYO Hotels Jeddah",
    nameAr: "فنادق أويو جدة",
    city: "Jeddah",
    location: "Multiple Locations",
    description: "Budget-friendly hotel chain with small event spaces for intimate gatherings",
    descriptionAr: "سلسلة فنادق اقتصادية مع مساحات فعاليات صغيرة للتجمعات الحميمة",
    venueType: "hotel",
    capacity: 100,
    imageUrl: "https://example.com/oyo-jeddah.jpg",
    imageUrls: ["https://example.com/oyo-jeddah.jpg"],
    amenities: ["Budget Friendly", "Small Events", "Multiple Locations", "Basic Amenities"],
    contactPhone: "+966-12-123-4799",
    contactEmail: "events@oyohotels.com",
    website: "https://www.oyohotels.com/jeddah",
    priceRange: "500-1500 SAR per event",
    rating: 3.8,
    verified: true,
  },

  // More Shopping Centers & Malls (8 venues)
  {
    name: "Mall of Arabia Event Plaza",
    nameAr: "ساحة فعاليات مول العرب",
    city: "Jeddah",
    location: "Al Zahra District",
    description: "Large shopping mall with central plaza for community events and exhibitions",
    descriptionAr: "مول تسوق كبير مع ساحة مركزية للفعاليات المجتمعية والمعارض",
    venueType: "mall",
    capacity: 500,
    imageUrl: "https://example.com/mall-arabia.jpg",
    imageUrls: ["https://example.com/mall-arabia.jpg"],
    amenities: ["Central Plaza", "Community Events", "Exhibitions", "High Traffic"],
    contactPhone: "+966-12-234-5800",
    contactEmail: "events@mallarabia.com",
    website: "https://www.mallarabia.com/events",
    priceRange: "1500-4000 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Aziz Mall Event Center",
    nameAr: "مركز فعاليات العزيز مول",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Popular neighborhood mall with event space for product launches and promotions",
    descriptionAr: "مول شعبي في الحي مع مساحة فعاليات لإطلاق المنتجات والترويج",
    venueType: "mall",
    capacity: 200,
    imageUrl: "https://example.com/aziz-mall.jpg",
    imageUrls: ["https://example.com/aziz-mall.jpg"],
    amenities: ["Product Launches", "Promotions", "Neighborhood Setting", "Easy Access"],
    contactPhone: "+966-12-345-6801",
    contactEmail: "events@azizmall.com",
    website: "https://www.azizmall.com/events",
    priceRange: "800-2200 SAR per event",
    rating: 4.0,
    verified: true,
  },

  // More Restaurants & Dining Venues (15 venues)
  {
    name: "Lusin Armenian Restaurant",
    nameAr: "مطعم لوسين الأرمني",
    city: "Jeddah",
    location: "Prince Sultan Road",
    description: "Authentic Armenian restaurant with private dining rooms for special occasions",
    descriptionAr: "مطعم أرمني أصيل مع غرف طعام خاصة للمناسبات الخاصة",
    venueType: "restaurant",
    capacity: 120,
    imageUrl: "https://example.com/lusin.jpg",
    imageUrls: ["https://example.com/lusin.jpg"],
    amenities: ["Armenian Cuisine", "Private Dining", "Authentic Experience", "Special Occasions"],
    contactPhone: "+966-12-456-7802",
    contactEmail: "events@lusin.com",
    website: "https://www.lusin.com/events",
    priceRange: "1000-2800 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Al Deyafa Restaurant",
    nameAr: "مطعم الضيافة",
    city: "Jeddah",
    location: "Corniche Road",
    description: "Traditional Saudi hospitality restaurant with majlis-style seating",
    descriptionAr: "مطعم ضيافة سعودي تقليدي مع جلسات على طراز المجلس",
    venueType: "restaurant",
    capacity: 180,
    imageUrl: "https://example.com/al-deyafa.jpg",
    imageUrls: ["https://example.com/al-deyafa.jpg"],
    amenities: ["Majlis Seating", "Traditional Hospitality", "Saudi Cuisine", "Cultural Experience"],
    contactPhone: "+966-12-567-8803",
    contactEmail: "events@aldeyafa.com",
    website: "https://www.aldeyafa.com/events",
    priceRange: "900-2500 SAR per event",
    rating: 4.3,
    verified: true,
  },

  // More Wedding Halls (10 venues)
  {
    name: "Emerald Palace Wedding Hall",
    nameAr: "قاعة قصر الزمرد",
    city: "Jeddah",
    location: "Al Faisaliyah District",
    description: "Emerald-themed luxury wedding venue with green and gold decor",
    descriptionAr: "قاعة أفراح فاخرة بطابع الزمرد مع ديكور أخضر وذهبي",
    venueType: "wedding_hall",
    capacity: 650,
    imageUrl: "https://example.com/emerald-palace.jpg",
    imageUrls: ["https://example.com/emerald-palace.jpg"],
    amenities: ["Emerald Theme", "Luxury Venue", "Green Gold Decor", "Large Capacity"],
    contactPhone: "+966-12-678-9804",
    contactEmail: "info@emeraldpalacehall.com",
    website: "https://www.emeraldpalacehall.com",
    priceRange: "4000-9500 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Sapphire Dreams Wedding Venue",
    nameAr: "قاعة أحلام الياقوت الأزرق",
    city: "Jeddah",
    location: "King Fahad Road",
    description: "Blue sapphire-themed wedding hall with ocean-inspired decor",
    descriptionAr: "قاعة أفراح بطابع الياقوت الأزرق مع ديكور مستوحى من المحيط",
    venueType: "wedding_hall",
    capacity: 520,
    imageUrl: "https://example.com/sapphire-dreams.jpg",
    imageUrls: ["https://example.com/sapphire-dreams.jpg"],
    amenities: ["Sapphire Theme", "Ocean Decor", "Blue Color Scheme", "Modern Design"],
    contactPhone: "+966-12-789-0805",
    contactEmail: "info@sapphiredreamshall.com",
    website: "https://www.sapphiredreamshall.com",
    priceRange: "3600-8800 SAR per event",
    rating: 4.4,
    verified: true,
  },

  // Entertainment & Recreational Venues (12 venues)
  {
    name: "Sparky's Family Entertainment Center",
    nameAr: "مركز سباركيز للترفيه العائلي",
    city: "Jeddah",
    location: "Red Sea Mall",
    description: "Family entertainment center with party rooms for children's events",
    descriptionAr: "مركز ترفيه عائلي مع غرف حفلات لفعاليات الأطفال",
    venueType: "entertainment",
    capacity: 100,
    imageUrl: "https://example.com/sparkys.jpg",
    imageUrls: ["https://example.com/sparkys.jpg"],
    amenities: ["Kids Parties", "Family Entertainment", "Party Rooms", "Games & Activities"],
    contactPhone: "+966-12-890-1806",
    contactEmail: "events@sparkys.com",
    website: "https://www.sparkys.com/events",
    priceRange: "800-2000 SAR per event",
    rating: 4.2,
    verified: true,
  },
  {
    name: "Bowling Lounge Jeddah",
    nameAr: "صالة البولينغ جدة",
    city: "Jeddah",
    location: "Stars Avenue Mall",
    description: "Modern bowling alley with private lanes and event packages",
    descriptionAr: "صالة بولينغ حديثة مع ممرات خاصة وحزم فعاليات",
    venueType: "entertainment",
    capacity: 80,
    imageUrl: "https://example.com/bowling-lounge.jpg",
    imageUrls: ["https://example.com/bowling-lounge.jpg"],
    amenities: ["Bowling Lanes", "Private Events", "Corporate Parties", "Team Building"],
    contactPhone: "+966-12-901-2807",
    contactEmail: "events@bowlinglounge.com",
    website: "https://www.bowlinglounge.com/events",
    priceRange: "1200-3000 SAR per event",
    rating: 4.1,
    verified: true,
  },

  // Outdoor & Garden Venues (8 venues)
  {
    name: "Jeddah Waterfront Park",
    nameAr: "متنزه الواجهة البحرية بجدة",
    city: "Jeddah",
    location: "Corniche Area",
    description: "Public waterfront park with pavilions for outdoor events and gatherings",
    descriptionAr: "متنزه عام على الواجهة البحرية مع أجنحة للفعاليات والتجمعات الخارجية",
    venueType: "outdoor",
    capacity: 400,
    imageUrl: "https://example.com/waterfront-park.jpg",
    imageUrls: ["https://example.com/waterfront-park.jpg"],
    amenities: ["Waterfront Views", "Public Park", "Pavilions", "Natural Setting"],
    contactPhone: "+966-12-012-3808",
    contactEmail: "events@jeddahparks.gov.sa",
    website: "https://www.jeddahparks.gov.sa/waterfront",
    priceRange: "600-1800 SAR per event",
    rating: 4.0,
    verified: true,
  },
  {
    name: "Al Shallal Theme Park Event Area",
    nameAr: "منطقة فعاليات الشلال الترفيهي",
    city: "Jeddah",
    location: "Al Shallal Theme Park",
    description: "Theme park with designated event areas for parties and celebrations",
    descriptionAr: "مدينة ملاهي مع مناطق مخصصة للفعاليات والحفلات والاحتفالات",
    venueType: "entertainment",
    capacity: 250,
    imageUrl: "https://example.com/al-shallal.jpg",
    imageUrls: ["https://example.com/al-shallal.jpg"],
    amenities: ["Theme Park Setting", "Rides & Attractions", "Family Events", "Party Areas"],
    contactPhone: "+966-12-123-4809",
    contactEmail: "events@alshallal.com",
    website: "https://www.alshallal.com/events",
    priceRange: "1500-3500 SAR per event",
    rating: 4.3,
    verified: true,
  },

  // More Cultural Centers & Museums (10 venues)
  {
    name: "Jeddah Art Museum",
    nameAr: "متحف جدة للفنون",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Contemporary art museum with gallery spaces for art exhibitions and cultural events",
    descriptionAr: "متحف فنون معاصرة مع مساحات معرض للمعارض الفنية والأحداث الثقافية",
    venueType: "cultural_center",
    capacity: 200,
    imageUrl: "https://example.com/jeddah-art-museum.jpg",
    imageUrls: ["https://example.com/jeddah-art-museum.jpg"],
    amenities: ["Art Galleries", "Cultural Events", "Educational Programs", "Modern Facilities"],
    contactPhone: "+966-12-234-5810",
    contactEmail: "events@jeddahartmuseum.gov.sa",
    website: "https://www.jeddahartmuseum.gov.sa/events",
    priceRange: "800-2200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Islamic Heritage Foundation",
    nameAr: "مؤسسة التراث الإسلامي",
    city: "Jeddah",
    location: "Al Balad",
    description: "Heritage foundation showcasing Islamic culture and traditions with event spaces",
    descriptionAr: "مؤسسة تراث تعرض الثقافة والتقاليد الإسلامية مع مساحات فعاليات",
    venueType: "cultural_center",
    capacity: 180,
    imageUrl: "https://example.com/islamic-heritage.jpg",
    imageUrls: ["https://example.com/islamic-heritage.jpg"],
    amenities: ["Islamic Heritage", "Cultural Programs", "Traditional Architecture", "Educational Events"],
    contactPhone: "+966-12-345-6811",
    contactEmail: "events@islamicheritage.org.sa",
    website: "https://www.islamicheritage.org.sa/events",
    priceRange: "600-1800 SAR per event",
    rating: 4.2,
    verified: true,
  },

  // More Corporate & Business Centers (12 venues)  
  {
    name: "Jeddah Business Center",
    nameAr: "مركز جدة للأعمال",
    city: "Jeddah",
    location: "Prince Abdulmajeed Street",
    description: "Multi-purpose business center with flexible meeting rooms and conference facilities",
    descriptionAr: "مركز أعمال متعدد الأغراض مع غرف اجتماعات مرنة ومرافق مؤتمرات",
    venueType: "convention_center",
    capacity: 400,
    imageUrl: "https://example.com/jbc.jpg",
    imageUrls: ["https://example.com/jbc.jpg"],
    amenities: ["Flexible Meeting Rooms", "Conference Facilities", "Business Services", "Central Location"],
    contactPhone: "+966-12-456-7812",
    contactEmail: "events@jeddahbusiness.com",
    website: "https://www.jeddahbusiness.com/events",
    priceRange: "1200-3200 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "King Fahd Hospital Conference Hall",
    nameAr: "قاعة مؤتمرات مستشفى الملك فهد",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Medical conference facility with state-of-the-art equipment for professional gatherings",
    descriptionAr: "مرفق مؤتمرات طبية مع معدات متطورة للتجمعات المهنية",
    venueType: "convention_center",
    capacity: 300,
    imageUrl: "https://example.com/kfh-conference.jpg",
    imageUrls: ["https://example.com/kfh-conference.jpg"],
    amenities: ["Medical Facility", "State-of-the-art Equipment", "Professional Events", "Healthcare Focus"],
    contactPhone: "+966-12-567-8813",
    contactEmail: "conferences@kfh.med.sa",
    website: "https://www.kfh.med.sa/conferences",
    priceRange: "1500-3800 SAR per event",
    rating: 4.3,
    verified: true,
  },

  // Additional Wedding Halls (15 venues)
  {
    name: "Ruby Rose Wedding Palace",
    nameAr: "قصر وردة الياقوت الأحمر",
    city: "Jeddah",
    location: "Al Zahra District", 
    description: "Ruby-themed wedding palace with red rose garden and luxury amenities",
    descriptionAr: "قصر أفراح بطابع الياقوت الأحمر مع حديقة ورود حمراء ومرافق فاخرة",
    venueType: "wedding_hall",
    capacity: 700,
    imageUrl: "https://example.com/ruby-rose.jpg",
    imageUrls: ["https://example.com/ruby-rose.jpg"],
    amenities: ["Ruby Theme", "Rose Garden", "Luxury Amenities", "Palace Setting"],
    contactPhone: "+966-12-678-9814",
    contactEmail: "info@rubyrosehall.com",
    website: "https://www.rubyrosehall.com",
    priceRange: "4200-10800 SAR per event",
    rating: 4.8,
    verified: true,
  },
  {
    name: "Topaz Dreams Wedding Hall",
    nameAr: "قاعة أحلام التوباز",
    city: "Jeddah",
    location: "King Abdulaziz Road",
    description: "Topaz-themed venue with warm golden lighting and contemporary design",
    descriptionAr: "قاعة بطابع التوباز مع إضاءة ذهبية دافئة وتصميم معاصر",
    venueType: "wedding_hall",
    capacity: 480,
    imageUrl: "https://example.com/topaz-dreams.jpg",
    imageUrls: ["https://example.com/topaz-dreams.jpg"],
    amenities: ["Topaz Theme", "Golden Lighting", "Contemporary Design", "Warm Ambiance"],
    contactPhone: "+966-12-789-0815",
    contactEmail: "info@topazdreamshall.com",
    website: "https://www.topazdreamshall.com",
    priceRange: "3400-8000 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Amethyst Garden Wedding Venue",
    nameAr: "قاعة حديقة الجمشت",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Purple amethyst-themed garden wedding venue with outdoor ceremony space",
    descriptionAr: "قاعة حديقة أفراح بطابع الجمشت البنفسجي مع مساحة احتفال خارجية",
    venueType: "wedding_hall",
    capacity: 350,
    imageUrl: "https://example.com/amethyst-garden.jpg",
    imageUrls: ["https://example.com/amethyst-garden.jpg"],
    amenities: ["Amethyst Theme", "Garden Setting", "Outdoor Ceremony", "Purple Decor"],
    contactPhone: "+966-12-890-1816",
    contactEmail: "info@amethystgardenhall.com",
    website: "https://www.amethystgardenhall.com",
    priceRange: "2900-7100 SAR per event",
    rating: 4.4,
    verified: true,
  },

  // More Hotels (8 venues)
  {
    name: "Ibis Jeddah City Center",
    nameAr: "إبيس جدة سيتي سنتر",
    city: "Jeddah",
    location: "King Fahd Road",
    description: "Budget hotel with meeting rooms for small business events",
    descriptionAr: "فندق اقتصادي مع غرف اجتماعات للفعاليات التجارية الصغيرة",
    venueType: "hotel",
    capacity: 150,
    imageUrl: "https://example.com/ibis-jeddah.jpg",
    imageUrls: ["https://example.com/ibis-jeddah.jpg"],
    amenities: ["Budget Friendly", "Meeting Rooms", "City Center", "Basic Amenities"],
    contactPhone: "+966-12-901-2817",
    contactEmail: "events@ibis.com",
    website: "https://www.ibis.com/jeddah",
    priceRange: "600-1800 SAR per event",
    rating: 3.9,
    verified: true,
  },
  {
    name: "Golden Tulip Jeddah",
    nameAr: "جولدن تيوليب جدة",
    city: "Jeddah",
    location: "Madinah Road",
    description: "Mid-range hotel with versatile event spaces and conference rooms",
    descriptionAr: "فندق متوسط المدى مع مساحات فعاليات متنوعة وغرف مؤتمرات",
    venueType: "hotel",
    capacity: 300,
    imageUrl: "https://example.com/golden-tulip.jpg",
    imageUrls: ["https://example.com/golden-tulip.jpg"],
    amenities: ["Versatile Spaces", "Conference Rooms", "Mid-range Pricing", "Professional Service"],
    contactPhone: "+966-12-012-3818",
    contactEmail: "events@goldentulipjeddah.com",
    website: "https://www.goldentulip.com/jeddah",
    priceRange: "1000-2800 SAR per event",
    rating: 4.1,
    verified: true,
  },

  // More Restaurants (12 venues)
  {
    name: "Shababeek Restaurant",
    nameAr: "مطعم شبابيك",
    city: "Jeddah",
    location: "Tahlia Street",
    description: "Traditional Levantine restaurant with private dining areas",
    descriptionAr: "مطعم شامي تقليدي مع مناطق طعام خاصة",
    venueType: "restaurant",
    capacity: 140,
    imageUrl: "https://example.com/shababeek.jpg",
    imageUrls: ["https://example.com/shababeek.jpg"],
    amenities: ["Levantine Cuisine", "Private Dining", "Traditional Decor", "Authentic Food"],
    contactPhone: "+966-12-123-4819",
    contactEmail: "events@shababeek.com",
    website: "https://www.shababeek.com/events",
    priceRange: "1100-2900 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Mama Noura Restaurant",
    nameAr: "مطعم ماما نورا",
    city: "Jeddah",
    location: "Multiple Locations",
    description: "Popular Saudi chain restaurant with family-style dining rooms",
    descriptionAr: "سلسلة مطاعم سعودية شهيرة مع غرف طعام عائلية",
    venueType: "restaurant",
    capacity: 200,
    imageUrl: "https://example.com/mama-noura.jpg",
    imageUrls: ["https://example.com/mama-noura.jpg"],
    amenities: ["Family Dining", "Saudi Cuisine", "Multiple Locations", "Casual Atmosphere"],
    contactPhone: "+966-12-234-5820",
    contactEmail: "events@mamanoura.com",
    website: "https://www.mamanoura.com/events",
    priceRange: "700-2100 SAR per event",
    rating: 4.2,
    verified: true,
  },

  // More Entertainment Venues (8 venues)
  {
    name: "Atallah Happy Land Park",
    nameAr: "منتزه عطالله هابي لاند",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Family amusement park with event pavilions and party areas",
    descriptionAr: "مدينة ملاهي عائلية مع أجنحة فعاليات ومناطق حفلات",
    venueType: "entertainment",
    capacity: 300,
    imageUrl: "https://example.com/atallah-park.jpg",
    imageUrls: ["https://example.com/atallah-park.jpg"],
    amenities: ["Amusement Rides", "Party Areas", "Family Events", "Children's Activities"],
    contactPhone: "+966-12-345-6821",
    contactEmail: "events@atallahpark.com",
    website: "https://www.atallahpark.com/events",
    priceRange: "1200-3200 SAR per event",
    rating: 4.0,
    verified: true,
  },
  {
    name: "Ice Land Theme Park",
    nameAr: "مدينة آيس لاند الترفيهية",
    city: "Jeddah",
    location: "Red Sea Mall",
    description: "Indoor ice-themed entertainment center with party rooms",
    descriptionAr: "مركز ترفيه داخلي بطابع الثلج مع غرف حفلات",
    venueType: "entertainment",
    capacity: 120,
    imageUrl: "https://example.com/ice-land.jpg",
    imageUrls: ["https://example.com/ice-land.jpg"],
    amenities: ["Ice Theme", "Indoor Activities", "Party Rooms", "Unique Experience"],
    contactPhone: "+966-12-456-7822",
    contactEmail: "events@iceland.com",
    website: "https://www.iceland.com/events",
    priceRange: "1500-3800 SAR per event",
    rating: 4.1,
    verified: true,
  },

  // Additional Outdoor Venues (5 venues)
  {
    name: "King Abdullah Park",
    nameAr: "حديقة الملك عبدالله",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "Large public park with event pavilions and outdoor celebration areas",
    descriptionAr: "حديقة عامة كبيرة مع أجنحة فعاليات ومناطق احتفال خارجية",
    venueType: "outdoor",
    capacity: 600,
    imageUrl: "https://example.com/king-abdullah-park.jpg",
    imageUrls: ["https://example.com/king-abdullah-park.jpg"],
    amenities: ["Public Park", "Event Pavilions", "Natural Setting", "Large Capacity"],
    contactPhone: "+966-12-567-8823",
    contactEmail: "events@jeddahparks.gov.sa",
    website: "https://www.jeddahparks.gov.sa/kingabdullah",
    priceRange: "800-2400 SAR per event",
    rating: 4.2,
    verified: true,
  },

  // Final Additional Venues to reach 100+ (15 venues)
  {
    name: "Movenpick Hotel Jeddah City Star",
    nameAr: "موڤنبيك جدة ستي ستار",
    city: "Jeddah",
    location: "Al Andalus District",
    description: "Luxury city hotel with rooftop event spaces and panoramic city views",
    descriptionAr: "فندق مدينة فاخر مع مساحات فعاليات على السطح وإطلالات بانورامية على المدينة",
    venueType: "hotel",
    capacity: 450,
    imageUrl: "https://example.com/movenpick-city-star.jpg",
    imageUrls: ["https://example.com/movenpick-city-star.jpg"],
    amenities: ["Rooftop Events", "City Views", "Luxury Amenities", "Central Location"],
    contactPhone: "+966-12-678-9824",
    contactEmail: "events@movenpickcitystar.com",
    website: "https://www.movenpick.com/jeddah-citystar",
    priceRange: "1800-4200 SAR per event",
    rating: 4.4,
    verified: true,
  },
  {
    name: "Al Hamra Palace Wedding Hall",
    nameAr: "قاعة قصر الحمراء",
    city: "Jeddah",
    location: "Al Hamra District",
    description: "Andalusian-inspired wedding palace with traditional Islamic architecture",
    descriptionAr: "قصر أفراح مستوحى من الأندلس بالعمارة الإسلامية التقليدية",
    venueType: "wedding_hall",
    capacity: 600,
    imageUrl: "https://example.com/al-hamra-palace.jpg",
    imageUrls: ["https://example.com/al-hamra-palace.jpg"],
    amenities: ["Andalusian Design", "Islamic Architecture", "Traditional Elements", "Cultural Heritage"],
    contactPhone: "+966-12-789-0825",
    contactEmail: "info@alhamrapalace.com",
    website: "https://www.alhamrapalace.com",
    priceRange: "3800-9200 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Al Khozama Restaurant Events",
    nameAr: "مطعم الخزامى للفعاليات",
    city: "Jeddah",
    location: "Corniche Road",
    description: "Upscale seafood restaurant with private dining rooms overlooking the Red Sea",
    descriptionAr: "مطعم مأكولات بحرية راقي مع غرف طعام خاصة مطلة على البحر الأحمر",
    venueType: "restaurant",
    capacity: 160,
    imageUrl: "https://example.com/al-khozama.jpg",
    imageUrls: ["https://example.com/al-khozama.jpg"],
    amenities: ["Red Sea Views", "Seafood Cuisine", "Private Dining", "Waterfront Location"],
    contactPhone: "+966-12-890-1826",
    contactEmail: "events@alkhozama.com",
    website: "https://www.alkhozama.com/events",
    priceRange: "1200-3400 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Jeddah Science Museum",
    nameAr: "متحف جدة للعلوم",
    city: "Jeddah",
    location: "King Abdulaziz University District",
    description: "Interactive science museum with event halls for educational and corporate events",
    descriptionAr: "متحف علوم تفاعلي مع قاعات فعاليات للأحداث التعليمية والمؤسسية",
    venueType: "cultural_center",
    capacity: 280,
    imageUrl: "https://example.com/science-museum.jpg",
    imageUrls: ["https://example.com/science-museum.jpg"],
    amenities: ["Interactive Exhibits", "Educational Programs", "Modern Facilities", "Corporate Events"],
    contactPhone: "+966-12-901-2827",
    contactEmail: "events@jeddahscience.edu.sa",
    website: "https://www.jeddahscience.edu.sa/events",
    priceRange: "1000-2800 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "Dallah Avenues Mall Event Plaza",
    nameAr: "ساحة فعاليات دلة أفينيوز مول",
    city: "Jeddah",
    location: "Dallah Avenues Mall",
    description: "Premium shopping mall with luxury event spaces and high-end retail environment",
    descriptionAr: "مول تسوق فاخر مع مساحات فعاليات راقية وبيئة تجزئة عالية الجودة",
    venueType: "mall",
    capacity: 400,
    imageUrl: "https://example.com/dallah-avenues.jpg",
    imageUrls: ["https://example.com/dallah-avenues.jpg"],
    amenities: ["Luxury Shopping", "Premium Events", "High-end Retail", "Modern Design"],
    contactPhone: "+966-12-012-3828",
    contactEmail: "events@dallahavenues.com",
    website: "https://www.dallahavenues.com/events",
    priceRange: "2000-5000 SAR per event",
    rating: 4.5,
    verified: true,
  },
  {
    name: "Jeddah Fountain Garden",
    nameAr: "حديقة نافورة جدة",
    city: "Jeddah",
    location: "King Fahd Fountain Area",
    description: "Scenic garden venue near the famous King Fahd Fountain with outdoor event spaces",
    descriptionAr: "حديقة ذات مناظر خلابة بالقرب من نافورة الملك فهد الشهيرة مع مساحات فعاليات خارجية",
    venueType: "outdoor",
    capacity: 350,
    imageUrl: "https://example.com/fountain-garden.jpg",
    imageUrls: ["https://example.com/fountain-garden.jpg"],
    amenities: ["Fountain Views", "Garden Setting", "Outdoor Events", "Scenic Location"],
    contactPhone: "+966-12-123-4829",
    contactEmail: "events@fountaingarden.gov.sa",
    website: "https://www.jeddahparks.gov.sa/fountain-garden",
    priceRange: "1000-2800 SAR per event",
    rating: 4.3,
    verified: true,
  },
  {
    name: "Chuck E. Cheese Jeddah",
    nameAr: "تشاك إي تشيز جدة",
    city: "Jeddah",
    location: "Mall of Arabia",
    description: "Family entertainment center specializing in children's birthday parties and events",
    descriptionAr: "مركز ترفيه عائلي متخصص في حفلات أعياد الميلاد والفعاليات للأطفال",
    venueType: "entertainment",
    capacity: 150,
    imageUrl: "https://example.com/chuck-e-cheese.jpg",
    imageUrls: ["https://example.com/chuck-e-cheese.jpg"],
    amenities: ["Kids Parties", "Gaming Area", "Pizza Restaurant", "Character Shows"],
    contactPhone: "+966-12-234-5830",
    contactEmail: "events@chuckecheese.com.sa",
    website: "https://www.chuckecheese.com.sa/events",
    priceRange: "800-2200 SAR per event",
    rating: 4.0,
    verified: true,
  },
  {
    name: "Jeddah Yacht Club",
    nameAr: "نادي جدة لليخوت",
    city: "Jeddah",
    location: "Marina District",
    description: "Exclusive yacht club with waterfront event spaces and marina views",
    descriptionAr: "نادي يخوت حصري مع مساحات فعاليات على الواجهة البحرية وإطلالات المارينا",
    venueType: "outdoor",
    capacity: 200,
    imageUrl: "https://example.com/yacht-club.jpg",
    imageUrls: ["https://example.com/yacht-club.jpg"],
    amenities: ["Marina Views", "Yacht Access", "Exclusive Setting", "Waterfront Events"],
    contactPhone: "+966-12-345-6831",
    contactEmail: "events@jeddahyachtclub.com",
    website: "https://www.jeddahyachtclub.com/events",
    priceRange: "2500-6000 SAR per event",
    rating: 4.6,
    verified: true,
  },
  {
    name: "Panorama Mall Event Center",
    nameAr: "مركز فعاليات بانوراما مول",
    city: "Jeddah",
    location: "Panorama Mall, Hera Street",
    description: "Community shopping mall with event center for local gatherings and celebrations",
    descriptionAr: "مول تسوق مجتمعي مع مركز فعاليات للتجمعات والاحتفالات المحلية",
    venueType: "mall",
    capacity: 300,
    imageUrl: "https://example.com/panorama-mall.jpg",
    imageUrls: ["https://example.com/panorama-mall.jpg"],
    amenities: ["Community Events", "Local Gatherings", "Shopping Environment", "Accessible Location"],
    contactPhone: "+966-12-456-7832",
    contactEmail: "events@panoramamall.com",
    website: "https://www.panoramamall.com/events",
    priceRange: "1000-2800 SAR per event",
    rating: 3.9,
    verified: true,
  },
  {
    name: "Al Rowad Private School Auditorium",
    nameAr: "قاعة محاضرات مدرسة الرواد الأهلية",
    city: "Jeddah",
    location: "Al Salamah District",
    description: "Private school auditorium available for educational seminars and community events",
    descriptionAr: "قاعة محاضرات مدرسة أهلية متاحة للندوات التعليمية والفعاليات المجتمعية",
    venueType: "community_center",
    capacity: 250,
    imageUrl: "https://example.com/al-rowad.jpg",
    imageUrls: ["https://example.com/al-rowad.jpg"],
    amenities: ["Educational Setting", "Community Events", "Modern AV", "School Environment"],
    contactPhone: "+966-12-567-8833",
    contactEmail: "events@alrowadschool.edu.sa",
    website: "https://www.alrowadschool.edu.sa/events",
    priceRange: "800-2000 SAR per event",
    rating: 4.0,
    verified: true,
  },
  {
    name: "Jeddah International Market Food Court",
    nameAr: "منطقة طعام السوق العالمي جدة",
    city: "Jeddah",
    location: "Al Rawdah District",
    description: "International food court with event space for food festivals and cultural celebrations",
    descriptionAr: "منطقة طعام عالمية مع مساحة فعاليات لمهرجانات الطعام والاحتفالات الثقافية",
    venueType: "restaurant",
    capacity: 300,
    imageUrl: "https://example.com/intl-market.jpg",
    imageUrls: ["https://example.com/intl-market.jpg"],
    amenities: ["International Cuisine", "Food Festivals", "Cultural Events", "Diverse Options"],
    contactPhone: "+966-12-678-9834",
    contactEmail: "events@jeddahintlmarket.com",
    website: "https://www.jeddahintlmarket.com/events",
    priceRange: "1200-3000 SAR per event",
    rating: 4.1,
    verified: true,
  },
  {
    name: "Roshan Waterfront Project Event Space",
    nameAr: "مساحة فعاليات مشروع روشن الواجهة البحرية",
    city: "Jeddah",
    location: "Jeddah Waterfront",
    description: "Modern waterfront development with contemporary event spaces and Red Sea views",
    descriptionAr: "تطوير واجهة بحرية حديث مع مساحات فعاليات معاصرة وإطلالات على البحر الأحمر",
    venueType: "outdoor",
    capacity: 500,
    imageUrl: "https://example.com/roshan-waterfront.jpg",
    imageUrls: ["https://example.com/roshan-waterfront.jpg"],
    amenities: ["Waterfront Development", "Modern Design", "Red Sea Views", "Contemporary Spaces"],
    contactPhone: "+966-12-789-0835",
    contactEmail: "events@roshanwaterfront.com",
    website: "https://www.roshanwaterfront.com/events",
    priceRange: "2200-5500 SAR per event",
    rating: 4.7,
    verified: true,
  }
];

// Function to seed venues
export async function seedVenues() {
  try {
    console.log("🌟 Starting venues seeding...");
    
    // Clear existing venues from Jeddah
    await db.delete(venues).where(eq(venues.city, "Jeddah"));
    console.log("🗑️ Cleared existing Jeddah venues");

    // Insert venues in batches to avoid timeout
    const batchSize = 10;
    for (let i = 0; i < venuesData.length; i += batchSize) {
      const batch = venuesData.slice(i, i + batchSize);
      await db.insert(venues).values(batch);
      console.log(`✅ Inserted venues ${i + 1}-${Math.min(i + batchSize, venuesData.length)} of ${venuesData.length}`);
    }

    console.log(`🎉 Successfully seeded ${venuesData.length} venues in Jeddah!`);
  } catch (error) {
    console.error("❌ Error seeding venues:", error);
    throw error;
  }
}