import { createConnection } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import { venues } from '../shared/schema';

const sql = createConnection(process.env.DATABASE_URL!);
const db = drizzle(sql);

const dammamVenues = [
  // ***** LUXURY HOTELS (25 venues) *****
  {
    name: "Sheraton Dammam Hotel & Convention Centre",
    name_ar: "فندق شيراتون الدمام ومركز المؤتمرات",
    venue_type: "hotel",
    capacity: 2000,
    price_per_event: 15000,
    city: "Dammam",
    address: "King Saud Street, Downtown Dammam",
    phone: "+966 13 834 8888",
    email: "reservations.dammam@sheraton.com",
    description: "Premier 5-star hotel featuring the largest convention center in Eastern Province with 3 grand ballrooms, state-of-the-art facilities, and panoramic Gulf views",
    amenities: ["convention_center", "ballroom", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Dana Rayhaan by Rotana",
    name_ar: "دانا الريحان من روتانا",
    venue_type: "hotel",
    capacity: 600,
    price_per_event: 12000,
    city: "Dammam",
    address: "Sails Roundabout, Dammam",
    phone: "+966 13 510 0000",
    email: "dana.dammam@rotana.com",
    description: "Ultra-modern 5-star hotel opened in 2022 with spacious ballroom, three meeting rooms, and 285 contemporary rooms offering city or Arabian Gulf views",
    amenities: ["ballroom", "meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Grand Hyatt Al Khobar",
    name_ar: "جراند حياة الخبر",
    venue_type: "hotel",
    capacity: 1200,
    price_per_event: 18000,
    city: "Al Khobar",
    address: "Al Khobar Waterfront, Eastern Province",
    phone: "+966 13 821 1234",
    email: "alkhobar.grand@hyatt.com",
    description: "World-class luxury hotel with elegant ballrooms, versatile meeting spaces, and prestigious waterfront location. Saudi Arabia's Leading Hotel 2023",
    amenities: ["ballroom", "meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning", "waterfront_view"],
  },
  {
    name: "Residence Inn by Marriott Dammam",
    name_ar: "ريزيدنس إن من ماريوت الدمام",
    venue_type: "hotel",
    capacity: 300,
    price_per_event: 8000,
    city: "Dammam",
    address: "Business District, Dammam",
    phone: "+966 13 832 0000",
    email: "dammam.residence@marriott.com",
    description: "Modern 4-star extended-stay hotel opened in 2022 with 134 furnished suites, business center, and flexible meeting spaces for corporate events",
    amenities: ["meeting_rooms", "business_center", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Golden Tulip Corniche Dammam",
    name_ar: "جولدن توليب كورنيش الدمام",
    venue_type: "hotel",
    capacity: 400,
    price_per_event: 9000,
    city: "Dammam",
    address: "Seashell Roundabout, Dammam Corniche",
    phone: "+966 13 827 7777",
    email: "info@goldentulip-dammam.com",
    description: "4-star hotel with traditional glamour positioned on iconic Seashell Roundabout, offering meeting facilities and elegant event spaces",
    amenities: ["meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning", "corniche_view"],
  },
  {
    name: "Novotel Dammam Business Park",
    name_ar: "نوفوتيل دمام بيزنس بارك",
    venue_type: "hotel",
    capacity: 500,
    price_per_event: 10000,
    city: "Dammam",
    address: "Al Khobar Highway, Business Park",
    phone: "+966 13 849 9999",
    email: "h6985@accor.com",
    description: "Contemporary 4-star business hotel with meeting rooms and event facilities, 40 minutes from King Fahd International Airport",
    amenities: ["meeting_rooms", "business_center", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "InterContinental Al Khobar",
    name_ar: "إنتركونتيننتال الخبر",
    venue_type: "hotel",
    capacity: 800,
    price_per_event: 14000,
    city: "Al Khobar",
    address: "Prince Faisal Bin Fahd Road, Al Khobar",
    phone: "+966 13 898 7777",
    email: "alkhobar@ihg.com",
    description: "Designed in 16th-century castle style, offering spacious and comfortable wedding halls and elegant event spaces",
    amenities: ["ballroom", "wedding_halls", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Le Meridien Al Khobar",
    name_ar: "لو مريديان الخبر",
    venue_type: "hotel",
    capacity: 600,
    price_per_event: 13000,
    city: "Al Khobar",
    address: "Prince Faisal Street, Al Khobar",
    phone: "+966 13 887 9999",
    email: "lemeridien.alkhobar@lemeridien.com",
    description: "Luxury hotel featuring the traditionally designed Al Dana Ballroom and sophisticated meeting facilities",
    amenities: ["ballroom", "meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Crowne Plaza Al Khobar",
    name_ar: "كراون بلازا الخبر",
    venue_type: "hotel",
    capacity: 500,
    price_per_event: 11000,
    city: "Al Khobar",
    address: "King Abdulaziz Road, Al Khobar",
    phone: "+966 13 896 6666",
    email: "alkhobar@crowneplaza.com",
    description: "Premium hotel offering wedding services with meticulous precision and professional event coordination",
    amenities: ["ballroom", "wedding_services", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Mövenpick Hotel Al Khobar",
    name_ar: "فندق موفنبيك الخبر",
    venue_type: "hotel",
    capacity: 700,
    price_per_event: 12500,
    city: "Al Khobar",
    address: "Corniche Road, Al Khobar",
    phone: "+966 13 887 9000",
    email: "hotel.alkhobar@movenpick.com",
    description: "Features the city's largest ballroom and well-designed bridal suite, perfect for grand celebrations and corporate events",
    amenities: ["ballroom", "bridal_suite", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Warwick Al Khobar Hotel",
    name_ar: "فندق وارويك الخبر",
    venue_type: "hotel",
    capacity: 250,
    price_per_event: 7000,
    city: "Al Khobar",
    address: "Downtown Al Khobar",
    phone: "+966 13 882 5555",
    email: "alkhobar@warwickhotels.com",
    description: "Boutique hotel with intimate meeting spaces and conference facilities in downtown Al Khobar",
    amenities: ["meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Dammam Palace Hotel",
    name_ar: "فندق قصر الدمام",
    venue_type: "hotel",
    capacity: 400,
    price_per_event: 8500,
    city: "Dammam",
    address: "King Saud Street, Dammam",
    phone: "+966 13 826 5000",
    email: "info@dammampalace.com",
    description: "Traditional palace-style hotel offering elegant wedding celebrations and corporate event facilities",
    amenities: ["ballroom", "wedding_halls", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Four Points by Sheraton Dammam",
    name_ar: "فور بوينتس شيراتون الدمام",
    venue_type: "hotel",
    capacity: 350,
    price_per_event: 9500,
    city: "Dammam",
    address: "Al Corniche Road, Dammam",
    phone: "+966 13 833 7777",
    email: "fourpoints.dammam@sheraton.com",
    description: "Modern hotel with flexible event spaces and professional meeting facilities overlooking the Arabian Gulf",
    amenities: ["meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning", "gulf_view"],
  },
  {
    name: "Howard Johnson by Wyndham Dammam",
    name_ar: "هوارد جونسون الدمام",
    venue_type: "hotel",
    capacity: 300,
    price_per_event: 7500,
    city: "Dammam",
    address: "Prince Mohammed Bin Fahd Road",
    phone: "+966 13 834 2222",
    email: "dammam@hojo.com",
    description: "Contemporary hotel with banquet halls and air conditioning, rated 4.6/5 for event hosting excellence",
    amenities: ["banquet_halls", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Radisson Hotel Dammam Industrial City",
    name_ar: "فندق راديسون المدينة الصناعية الدمام",
    venue_type: "hotel",
    capacity: 400,
    price_per_event: 8000,
    city: "Dammam",
    address: "Industrial City, Second Industrial Area",
    phone: "+966 13 857 1111",
    email: "info.dammam@radisson.com",
    description: "Business-focused hotel with apartments and banquet facilities, rated 4.2/5 for corporate events and meetings",
    amenities: ["banquet_halls", "business_center", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },

  // Additional 10 boutique/business hotels
  {
    name: "Al Gosaibi Hotel",
    name_ar: "فندق القصيبي",
    venue_type: "hotel",
    capacity: 200,
    price_per_event: 6000,
    city: "Al Khobar",
    address: "Dhahran Street, Al Khobar",
    phone: "+966 13 894 4444",
    email: "info@algosaibihotel.com",
    description: "Historic hotel with traditional Arabian hospitality and modern conference facilities",
    amenities: ["meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Dhahran International Hotel",
    name_ar: "فندق الظهران الدولي",
    venue_type: "hotel",
    capacity: 350,
    price_per_event: 8500,
    city: "Dhahran",
    address: "Saudi Aramco Residential Camp Road",
    phone: "+966 13 891 5555",
    email: "reservations@dhahranhotel.com",
    description: "International business hotel serving the oil industry with professional meeting facilities and corporate event spaces",
    amenities: ["meeting_rooms", "business_center", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Coral Island Resort",
    name_ar: "منتجع جزيرة المرجان",
    venue_type: "hotel",
    capacity: 250,
    price_per_event: 7000,
    city: "Dammam",
    address: "Half Moon Bay, Dammam",
    phone: "+966 13 857 7777",
    email: "info@coralislandresort.com",
    description: "Beachfront resort with traditional heritage village and unique outdoor event spaces",
    amenities: ["outdoor_spaces", "heritage_village", "catering", "parking", "wifi", "air_conditioning", "beach_access"],
  },
  {
    name: "Gulf Palace Hotel",
    name_ar: "فندق قصر الخليج",
    venue_type: "hotel",
    capacity: 300,
    price_per_event: 7500,
    city: "Dammam",
    address: "Corniche Road, Dammam",
    phone: "+966 13 832 1111",
    email: "gulf.palace@gulfpalacehotel.com",
    description: "Waterfront hotel with panoramic Gulf views and elegant banquet facilities",
    amenities: ["banquet_halls", "catering", "av_equipment", "parking", "wifi", "air_conditioning", "gulf_view"],
  },
  {
    name: "Eastern Province Hotel",
    name_ar: "فندق المنطقة الشرقية",
    venue_type: "hotel",
    capacity: 200,
    price_per_event: 6500,
    city: "Dammam",
    address: "King Abdulaziz Street, Dammam",
    phone: "+966 13 827 3333",
    email: "info@easternprovincehotel.com",
    description: "Regional business hotel with flexible meeting spaces and traditional Arabian hospitality",
    amenities: ["meeting_rooms", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Sunset Beach Resort",
    name_ar: "منتجع شاطئ الغروب",
    venue_type: "hotel",
    capacity: 180,
    price_per_event: 6000,
    city: "Al Khobar",
    address: "Corniche Beach, Al Khobar",
    phone: "+966 13 894 7777",
    email: "sunset.beach@resort.com",
    description: "Beachfront resort with outdoor event spaces and stunning sunset views over the Arabian Gulf",
    amenities: ["outdoor_spaces", "beach_access", "catering", "parking", "wifi", "air_conditioning", "sunset_view"],
  },
  {
    name: "City Center Hotel Dammam",
    name_ar: "فندق سيتي سنتر الدمام",
    venue_type: "hotel",
    capacity: 250,
    price_per_event: 7000,
    city: "Dammam",
    address: "City Center, Dammam",
    phone: "+966 13 835 6666",
    email: "citycenter.dammam@hotels.com",
    description: "Central location hotel with modern conference facilities and business meeting rooms",
    amenities: ["conference_rooms", "business_center", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Aramco Guesthouse",
    name_ar: "بيت ضيافة أرامكو",
    venue_type: "hotel",
    capacity: 150,
    price_per_event: 5000,
    city: "Dhahran",
    address: "Saudi Aramco Compound, Dhahran",
    phone: "+966 13 876 4444",
    email: "guesthouse@aramco.com",
    description: "Exclusive corporate facility with premium meeting rooms and executive conference facilities",
    amenities: ["conference_rooms", "executive_facilities", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Sharq Hotel",
    name_ar: "فندق الشرق",
    venue_type: "hotel",
    capacity: 180,
    price_per_event: 5500,
    city: "Dammam",
    address: "Al Shatea District, Dammam",
    phone: "+966 13 828 9999",
    email: "alsharq.hotel@hotels.com",
    description: "Traditional hotel in the coastal district with authentic Arabian event spaces",
    amenities: ["traditional_halls", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Marina Bay Hotel",
    name_ar: "فندق خليج المارينا",
    venue_type: "hotel",
    capacity: 220,
    price_per_event: 6500,
    city: "Al Khobar",
    address: "Marina District, Al Khobar",
    phone: "+966 13 897 2222",
    email: "marina.bay@hotels.com",
    description: "Modern marina hotel with waterfront event spaces and yacht club facilities",
    amenities: ["waterfront_venues", "yacht_club", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },

  // ***** WEDDING HALLS (30 venues) *****
  {
    name: "Al Andalus Halls",
    name_ar: "قاعات الأندلس",
    venue_type: "wedding_hall",
    capacity: 800,
    price_per_event: 20000,
    city: "Dammam",
    address: "Al-Nozha, Al-Khansa District, Dammam",
    phone: "+966 13 842 7777",
    email: "info@alandalushalls.com",
    description: "Luxurious and elegant ballrooms designed to break from routine traditional events, featuring grand architecture and premium services",
    amenities: ["ballroom", "bridal_suite", "catering", "av_equipment", "parking", "wifi", "air_conditioning", "photography_area"],
  },
  {
    name: "Alandalus Hall Al Khobar",
    name_ar: "قاعة الأندلس الخبر",
    venue_type: "wedding_hall",
    capacity: 600,
    price_per_event: 18000,
    city: "Al Khobar",
    address: "Prince Fawaz Street, Al Khobar",
    phone: "+966 13 895 8888",
    email: "alkhobar@alandalushall.com",
    description: "Distinguished venue with traditional charm and modern design, featuring grand chandeliers, high ceilings, and customizable spaces",
    amenities: ["grand_chandeliers", "high_ceilings", "customizable_spaces", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Royal Palace Wedding Hall",
    name_ar: "قاعة القصر الملكي للأفراح",
    venue_type: "wedding_hall",
    capacity: 1000,
    price_per_event: 25000,
    city: "Dammam",
    address: "Al Faisaliah District, Dammam",
    phone: "+966 13 834 9999",
    email: "royalpalace@weddings.com",
    description: "Majestic wedding hall with royal-inspired décor, crystal chandeliers, and opulent ballroom facilities",
    amenities: ["royal_decor", "crystal_chandeliers", "opulent_ballroom", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Ben Sultan Hall",
    name_ar: "قاعة بن سلطان",
    venue_type: "wedding_hall",
    capacity: 700,
    price_per_event: 16000,
    city: "Dammam",
    address: "Al Shatea District, Dammam",
    phone: "+966 13 838 6666",
    email: "bensultan@halls.com",
    description: "One of the best wedding halls in Dammam, spacious and elegant with traditional Arabian design elements",
    amenities: ["spacious_hall", "traditional_design", "elegant_decor", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Leylati Hall",
    name_ar: "قاعة ليلاتي",
    venue_type: "wedding_hall",
    capacity: 500,
    price_per_event: 22000,
    city: "Dammam",
    address: "Corniche Road, Dammam",
    phone: "+966 13 829 7777",
    email: "leylati@elite.com",
    description: "Dammam's most elite wedding hall offering an ultra-glamorous experience with luxury amenities and sophisticated design",
    amenities: ["ultra_glamorous", "luxury_amenities", "sophisticated_design", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Al-Jawsaq Complex Halls",
    name_ar: "قاعات مجمع الجوسق",
    venue_type: "wedding_hall",
    capacity: 1500,
    price_per_event: 30000,
    city: "Dammam",
    address: "Prince Naif Street, Dammam",
    phone: "+966 13 845 9999",
    email: "aljawsaq@complex.com",
    description: "One of the largest and most luxurious halls in Eastern Province, designed for concerts, weddings, and major celebrations",
    amenities: ["large_capacity", "concert_facilities", "luxury_design", "multiple_halls", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Diamond Palace Hall",
    name_ar: "قاعة قصر الماس",
    venue_type: "wedding_hall",
    capacity: 600,
    price_per_event: 19000,
    city: "Al Khobar",
    address: "King Saud Road, Al Khobar",
    phone: "+966 13 892 5555",
    email: "diamond@palace.com",
    description: "Luxurious hall with diamond-themed décor, crystal fixtures, and premium wedding services",
    amenities: ["diamond_decor", "crystal_fixtures", "premium_services", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Pearl Palace Wedding Hall",
    name_ar: "قاعة قصر اللؤلؤ",
    venue_type: "wedding_hall",
    capacity: 550,
    price_per_event: 17000,
    city: "Dammam",
    address: "Al Mazruiyah District, Dammam",
    phone: "+966 13 836 4444",
    email: "pearl@palace.com",
    description: "Elegant hall with pearl-inspired design, featuring mother-of-pearl accents and refined Arabian luxury",
    amenities: ["pearl_design", "mother_of_pearl_accents", "arabian_luxury", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Golden Crown Hall",
    name_ar: "قاعة التاج الذهبي",
    venue_type: "wedding_hall",
    capacity: 750,
    price_per_event: 21000,
    city: "Dammam",
    address: "Al Khalidiyah District, Dammam",
    phone: "+966 13 841 8888",
    email: "goldencrown@weddings.com",
    description: "Majestic wedding venue with golden crown motifs, royal seating arrangements, and exceptional service",
    amenities: ["golden_decor", "royal_seating", "exceptional_service", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Crystal Gardens Hall",
    name_ar: "قاعة حدائق الكريستال",
    venue_type: "wedding_hall",
    capacity: 400,
    price_per_event: 15000,
    city: "Al Khobar",
    address: "Al Ulaya District, Al Khobar",
    phone: "+966 13 893 7777",
    email: "crystal@gardens.com",
    description: "Garden-themed wedding hall with crystal chandeliers, indoor garden features, and natural lighting",
    amenities: ["garden_theme", "crystal_chandeliers", "indoor_gardens", "natural_lighting", "catering", "av_equipment", "parking", "wifi"],
  },

  // Additional 20 wedding halls with various themes and capacities
  {
    name: "Moonlight Palace Hall",
    name_ar: "قاعة قصر ضوء القمر",
    venue_type: "wedding_hall",
    capacity: 450,
    price_per_event: 16500,
    city: "Dammam",
    address: "Al Ferdaws District, Dammam",
    phone: "+966 13 839 3333",
    email: "moonlight@palace.com",
    description: "Romantic wedding hall with moonlight-inspired lighting and celestial-themed décor",
    amenities: ["romantic_lighting", "celestial_decor", "bridal_suite", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Rose Garden Wedding Hall",
    name_ar: "قاعة حديقة الورد",
    venue_type: "wedding_hall",
    capacity: 350,
    price_per_event: 14000,
    city: "Al Khobar",
    address: "Al Bandariyah, Al Khobar",
    phone: "+966 13 891 6666",
    email: "rosegarden@weddings.com",
    description: "Floral-themed wedding venue with rose garden décor and outdoor ceremony space",
    amenities: ["floral_theme", "outdoor_ceremony", "garden_decor", "catering", "av_equipment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Sultan's Dream Hall",
    name_ar: "قاعة حلم السلطان",
    venue_type: "wedding_hall",
    capacity: 650,
    price_per_event: 18500,
    city: "Dammam",
    address: "Prince Turki Street, Dammam",
    phone: "+966 13 844 2222",
    email: "sultans@dream.com",
    description: "Opulent hall with Ottoman-inspired design, featuring traditional Islamic patterns and luxury furnishings",
    amenities: ["ottoman_design", "islamic_patterns", "luxury_furnishings", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Emerald Palace Hall",
    name_ar: "قاعة قصر الزمرد",
    venue_type: "wedding_hall",
    capacity: 500,
    price_per_event: 17500,
    city: "Al Khobar",
    address: "Al Thuqbah, Al Khobar",
    phone: "+966 13 896 1111",
    email: "emerald@palace.com",
    description: "Elegant venue with emerald-green color scheme and precious stone-inspired décor",
    amenities: ["emerald_theme", "precious_stone_decor", "elegant_design", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Starlight Ballroom",
    name_ar: "قاعة ضوء النجوم",
    venue_type: "wedding_hall",
    capacity: 600,
    price_per_event: 19500,
    city: "Dammam",
    address: "Al Anoud District, Dammam",
    phone: "+966 13 847 7777",
    email: "starlight@ballroom.com",
    description: "Celestial-themed ballroom with star-pattern lighting and cosmic décor elements",
    amenities: ["celestial_theme", "star_lighting", "cosmic_decor", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Ivory Tower Hall",
    name_ar: "قاعة برج العاج",
    venue_type: "wedding_hall",
    capacity: 400,
    price_per_event: 15500,
    city: "Dammam",
    address: "Al Shulah District, Dammam",
    phone: "+966 13 842 5555",
    email: "ivory@tower.com",
    description: "Sophisticated venue with ivory and gold color palette, classic elegance and timeless design",
    amenities: ["ivory_gold_theme", "classic_elegance", "timeless_design", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Opal Dreams Wedding Hall",
    name_ar: "قاعة أحلام العقيق",
    venue_type: "wedding_hall",
    capacity: 450,
    price_per_event: 16000,
    city: "Al Khobar",
    address: "Al Aqrabiyah, Al Khobar",
    phone: "+966 13 894 8888",
    email: "opal@dreams.com",
    description: "Mystical venue with opal-inspired iridescent décor and ethereal lighting effects",
    amenities: ["opal_theme", "iridescent_decor", "ethereal_lighting", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Majestic Crown Hall",
    name_ar: "قاعة التاج المهيب",
    venue_type: "wedding_hall",
    capacity: 700,
    price_per_event: 20500,
    city: "Dammam",
    address: "Al Badiyah District, Dammam",
    phone: "+966 13 848 9999",
    email: "majestic@crown.com",
    description: "Grand hall with majestic crown motifs, royal purple and gold décor, and throne-style seating",
    amenities: ["crown_motifs", "royal_decor", "throne_seating", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Sapphire Palace Wedding Hall",
    name_ar: "قاعة قصر الياقوت",
    venue_type: "wedding_hall",
    capacity: 550,
    price_per_event: 18000,
    city: "Al Khobar",
    address: "Al Rawdah District, Al Khobar",
    phone: "+966 13 899 4444",
    email: "sapphire@palace.com",
    description: "Luxury venue with sapphire blue theme, precious gemstone accents, and royal ambiance",
    amenities: ["sapphire_theme", "gemstone_accents", "royal_ambiance", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Golden Tulip Wedding Hall",
    name_ar: "قاعة التوليب الذهبي",
    venue_type: "wedding_hall",
    capacity: 380,
    price_per_event: 14500,
    city: "Dammam",
    address: "Al Rakah District, Dammam",
    phone: "+966 13 837 6666",
    email: "goldentulip@weddings.com",
    description: "Floral-inspired venue with golden tulip motifs and spring garden atmosphere",
    amenities: ["floral_inspiration", "tulip_motifs", "garden_atmosphere", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Phoenix Rising Hall",
    name_ar: "قاعة العنقاء الصاعدة",
    venue_type: "wedding_hall",
    capacity: 480,
    price_per_event: 17000,
    city: "Dammam",
    address: "Al Noor District, Dammam",
    phone: "+966 13 843 7777",
    email: "phoenix@rising.com",
    description: "Mythical-themed hall with phoenix motifs, fire-inspired lighting, and dramatic décor",
    amenities: ["mythical_theme", "phoenix_motifs", "dramatic_lighting", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Coral Reef Wedding Hall",
    name_ar: "قاعة الشعاب المرجانية",
    venue_type: "wedding_hall",
    capacity: 420,
    price_per_event: 15800,
    city: "Al Khobar",
    address: "Corniche District, Al Khobar",
    phone: "+966 13 892 3333",
    email: "coral@reef.com",
    description: "Ocean-themed venue with coral reef décor, aquatic elements, and seaside ambiance",
    amenities: ["ocean_theme", "coral_decor", "aquatic_elements", "seaside_ambiance", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Platinum Elite Hall",
    name_ar: "قاعة البلاتين النخبة",
    venue_type: "wedding_hall",
    capacity: 520,
    price_per_event: 19000,
    city: "Dammam",
    address: "Al Manar District, Dammam",
    phone: "+966 13 846 8888",
    email: "platinum@elite.com",
    description: "Ultra-modern venue with platinum accents, contemporary design, and state-of-the-art facilities",
    amenities: ["platinum_accents", "contemporary_design", "state_of_art_facilities", "bridal_suite", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Arabian Nights Hall",
    name_ar: "قاعة الليالي العربية",
    venue_type: "wedding_hall",
    capacity: 600,
    price_per_event: 18500,
    city: "Al Khobar",
    address: "Al Khuzama District, Al Khobar",
    phone: "+966 13 898 2222",
    email: "arabian@nights.com",
    description: "Traditional Arabian-themed venue with Bedouin tent elements, desert colors, and authentic décor",
    amenities: ["arabian_theme", "bedouin_elements", "desert_colors", "authentic_decor", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Celestial Stars Hall",
    name_ar: "قاعة النجوم السماوية",
    venue_type: "wedding_hall",
    capacity: 460,
    price_per_event: 16800,
    city: "Dammam",
    address: "Al Jalawiyah District, Dammam",
    phone: "+966 13 840 5555",
    email: "celestial@stars.com",
    description: "Astronomy-inspired venue with constellation lighting, celestial murals, and starry night atmosphere",
    amenities: ["astronomy_theme", "constellation_lighting", "celestial_murals", "starry_atmosphere", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Ruby Rose Wedding Hall",
    name_ar: "قاعة ياقوتة الورد",
    venue_type: "wedding_hall",
    capacity: 400,
    price_per_event: 15200,
    city: "Al Khobar",
    address: "Al Jisr District, Al Khobar",
    phone: "+966 13 895 7777",
    email: "ruby@rose.com",
    description: "Romantic venue with ruby red and rose pink color scheme, floral arrangements, and intimate lighting",
    amenities: ["romantic_theme", "ruby_rose_colors", "floral_arrangements", "intimate_lighting", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Grand Heritage Hall",
    name_ar: "قاعة التراث الكبرى",
    venue_type: "wedding_hall",
    capacity: 800,
    price_per_event: 22000,
    city: "Dammam",
    address: "Heritage Quarter, Dammam",
    phone: "+966 13 849 6666",
    email: "grand@heritage.com",
    description: "Traditional heritage venue with authentic Najdi architecture, historical artifacts, and cultural elements",
    amenities: ["heritage_theme", "najdi_architecture", "historical_artifacts", "cultural_elements", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Imperial Crown Wedding Hall",
    name_ar: "قاعة التاج الإمبراطوري",
    venue_type: "wedding_hall",
    capacity: 650,
    price_per_event: 21000,
    city: "Al Khobar",
    address: "Imperial District, Al Khobar",
    phone: "+966 13 897 1111",
    email: "imperial@crown.com",
    description: "Regal venue with imperial design, crown chandeliers, velvet furnishings, and royal treatment",
    amenities: ["imperial_design", "crown_chandeliers", "velvet_furnishings", "royal_treatment", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Jasmine Garden Hall",
    name_ar: "قاعة حديقة الياسمين",
    venue_type: "wedding_hall",
    capacity: 350,
    price_per_event: 13500,
    city: "Dammam",
    address: "Al Aziziyah District, Dammam",
    phone: "+966 13 835 4444",
    email: "jasmine@garden.com",
    description: "Botanical-themed venue with jasmine flower décor, garden arches, and natural fragrances",
    amenities: ["botanical_theme", "jasmine_decor", "garden_arches", "natural_fragrances", "catering", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Mystical Palace Hall",
    name_ar: "قاعة القصر الغامض",
    venue_type: "wedding_hall",
    capacity: 500,
    price_per_event: 17800,
    city: "Al Khobar",
    address: "Al Hamra District, Al Khobar",
    phone: "+966 13 893 9999",
    email: "mystical@palace.com",
    description: "Enchanting venue with mystical atmosphere, magical lighting effects, and fantasy-inspired décor",
    amenities: ["mystical_atmosphere", "magical_lighting", "fantasy_decor", "enchanting_design", "catering", "av_equipment", "parking", "wifi"],
  },

  // ***** CONFERENCE CENTERS & CONVENTION HALLS (25 venues) *****
  {
    name: "Dhahran International Exhibition Centre",
    name_ar: "مركز الظهران الدولي للمعارض",
    venue_type: "convention_center",
    capacity: 5000,
    price_per_event: 50000,
    city: "Dhahran",
    address: "Between Khobar, Dammam, and Dhahran",
    phone: "+966 13 891 0000",
    email: "info@dhahranexpo.com.sa",
    description: "Largest dedicated exhibition, conference and event space in Saudi Arabia with world-class facilities and prime strategic location",
    amenities: ["exhibition_halls", "conference_rooms", "trade_fair_facilities", "av_equipment", "catering", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "King Abdulaziz Center for World Culture (Ithra)",
    name_ar: "مركز الملك عبد العزيز الثقافي العالمي (إثراء)",
    venue_type: "convention_center",
    capacity: 2000,
    price_per_event: 40000,
    city: "Dhahran",
    address: "Saudi Aramco, Dhahran",
    phone: "+966 13 960 0000",
    email: "events@ithra.com",
    description: "18-story architectural masterpiece with museum, theater, cinema, library, and state-of-the-art event hosting capabilities",
    amenities: ["theater", "cinema", "exhibition_galleries", "conference_facilities", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Dammam Convention Center",
    name_ar: "مركز مؤتمرات الدمام",
    venue_type: "convention_center",
    capacity: 1500,
    price_per_event: 25000,
    city: "Dammam",
    address: "King Fahd Road, Dammam",
    phone: "+966 13 832 5000",
    email: "info@dammamconvention.com",
    description: "Modern convention facility with multiple meeting rooms, exhibition space, and professional event management services",
    amenities: ["meeting_rooms", "exhibition_space", "professional_services", "av_equipment", "catering", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Eastern Province Business Center",
    name_ar: "مركز الأعمال للمنطقة الشرقية",
    venue_type: "convention_center",
    capacity: 800,
    price_per_event: 18000,
    city: "Al Khobar",
    address: "Business District, Al Khobar",
    phone: "+966 13 887 3000",
    email: "business@epbc.com",
    description: "Corporate-focused venue with advanced technology, flexible meeting spaces, and executive conference facilities",
    amenities: ["executive_facilities", "advanced_technology", "flexible_spaces", "av_equipment", "business_center", "parking", "wifi"],
  },
  {
    name: "Dammam Chamber of Commerce Convention Hall",
    name_ar: "قاعة مؤتمرات غرفة تجارة الدمام",
    venue_type: "convention_center",
    capacity: 600,
    price_per_event: 15000,
    city: "Dammam",
    address: "Chamber of Commerce Building, Dammam",
    phone: "+966 13 857 1000",
    email: "events@dammamchamber.org.sa",
    description: "Professional venue for business conferences, trade meetings, and commercial events with full support services",
    amenities: ["business_facilities", "conference_rooms", "trade_meeting_spaces", "support_services", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "King Fahd University Conference Center",
    name_ar: "مركز مؤتمرات جامعة الملك فهد",
    venue_type: "convention_center",
    capacity: 1000,
    price_per_event: 20000,
    city: "Dhahran",
    address: "KFUPM Campus, Dhahran",
    phone: "+966 13 860 7000",
    email: "conferences@kfupm.edu.sa",
    description: "Academic conference center with state-of-the-art technology, lecture halls, and research presentation facilities",
    amenities: ["lecture_halls", "research_facilities", "academic_technology", "av_equipment", "catering", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Khobar International Conference Center",
    name_ar: "مركز الخبر الدولي للمؤتمرات",
    venue_type: "convention_center",
    capacity: 1200,
    price_per_event: 22000,
    city: "Al Khobar",
    address: "Corniche Road, Al Khobar",
    phone: "+966 13 896 8000",
    email: "info@khobarconference.com",
    description: "International standard conference facility with simultaneous translation, waterfront location, and premium services",
    amenities: ["simultaneous_translation", "waterfront_location", "premium_services", "conference_rooms", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Aramco Training Center Auditorium",
    name_ar: "قاعة مركز تدريب أرامكو",
    venue_type: "convention_center",
    capacity: 500,
    price_per_event: 12000,
    city: "Dhahran",
    address: "Saudi Aramco Training Center, Dhahran",
    phone: "+966 13 876 5000",
    email: "training.center@aramco.com",
    description: "Corporate training facility with advanced presentation technology and professional development resources",
    amenities: ["training_facilities", "presentation_technology", "professional_development", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Dammam Medical Complex Conference Hall",
    name_ar: "قاعة مؤتمرات المجمع الطبي بالدمام",
    venue_type: "convention_center",
    capacity: 400,
    price_per_event: 10000,
    city: "Dammam",
    address: "Medical Complex, King Fahd Road",
    phone: "+966 13 844 2000",
    email: "conferences@dmc.med.sa",
    description: "Medical conference facility specializing in healthcare seminars, medical training, and research presentations",
    amenities: ["medical_facilities", "healthcare_technology", "research_presentation", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Eastern Province Cultural Center",
    name_ar: "المركز الثقافي للمنطقة الشرقية",
    venue_type: "convention_center",
    capacity: 700,
    price_per_event: 16000,
    city: "Dammam",
    address: "Cultural District, Dammam",
    phone: "+966 13 839 4000",
    email: "cultural@epcc.org.sa",
    description: "Cultural venue with performance spaces, art galleries, and flexible event areas for cultural programs and conferences",
    amenities: ["performance_spaces", "art_galleries", "cultural_programs", "flexible_areas", "av_equipment", "catering", "parking", "wifi"],
  },

  // Additional 15 conference and business venues
  {
    name: "Gulf Business Conference Center",
    name_ar: "مركز مؤتمرات أعمال الخليج",
    venue_type: "convention_center",
    capacity: 350,
    price_per_event: 9000,
    city: "Al Khobar",
    address: "Gulf Business District, Al Khobar",
    phone: "+966 13 894 1000",
    email: "gulf@business.com",
    description: "Specialized business conference facility with Gulf regional focus and international connectivity",
    amenities: ["business_focus", "international_connectivity", "conference_rooms", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Petrochemical Industry Conference Hall",
    name_ar: "قاعة مؤتمرات الصناعات البتروكيماوية",
    venue_type: "convention_center",
    capacity: 600,
    price_per_event: 14000,
    city: "Dammam",
    address: "Industrial City, Second Industrial Area",
    phone: "+966 13 858 3000",
    email: "petrochem@conferences.com",
    description: "Industry-specific venue for petrochemical conferences, technical seminars, and industrial exhibitions",
    amenities: ["industrial_focus", "technical_facilities", "exhibition_space", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Eastern Province Technology Center",
    name_ar: "مركز التقنية للمنطقة الشرقية",
    venue_type: "convention_center",
    capacity: 450,
    price_per_event: 11000,
    city: "Al Khobar",
    address: "Technology Park, Al Khobar",
    phone: "+966 13 889 2000",
    email: "tech@epc.org.sa",
    description: "Technology-focused conference center with cutting-edge facilities and innovation showcases",
    amenities: ["technology_focus", "innovation_showcase", "cutting_edge_facilities", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Maritime Conference Center",
    name_ar: "مركز المؤتمرات البحرية",
    venue_type: "convention_center",
    capacity: 300,
    price_per_event: 8500,
    city: "Dammam",
    address: "Port Area, Dammam",
    phone: "+966 13 833 4000",
    email: "maritime@conferences.com",
    description: "Specialized venue for maritime industry conferences, shipping seminars, and port authority meetings",
    amenities: ["maritime_focus", "shipping_facilities", "port_connectivity", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Banking and Finance Conference Hall",
    name_ar: "قاعة مؤتمرات المصارف والمالية",
    venue_type: "convention_center",
    capacity: 400,
    price_per_event: 10500,
    city: "Al Khobar",
    address: "Financial District, Al Khobar",
    phone: "+966 13 892 7000",
    email: "banking@finance.com",
    description: "Financial sector conference facility with secure meeting rooms and banking industry technology",
    amenities: ["financial_focus", "secure_facilities", "banking_technology", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Environmental Sciences Conference Center",
    name_ar: "مركز مؤتمرات العلوم البيئية",
    venue_type: "convention_center",
    capacity: 250,
    price_per_event: 7500,
    city: "Dhahran",
    address: "Environmental Research Institute, Dhahran",
    phone: "+966 13 875 1000",
    email: "environmental@sciences.com",
    description: "Eco-friendly conference center specializing in environmental research, sustainability conferences, and green technology",
    amenities: ["eco_friendly", "sustainability_focus", "green_technology", "research_facilities", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "International Trade Conference Hall",
    name_ar: "قاعة مؤتمرات التجارة الدولية",
    venue_type: "convention_center",
    capacity: 500,
    price_per_event: 12500,
    city: "Dammam",
    address: "Trade Center, Dammam",
    phone: "+966 13 845 6000",
    email: "trade@international.com",
    description: "International trade-focused venue with customs facilities, trade exhibition space, and business networking areas",
    amenities: ["trade_focus", "customs_facilities", "exhibition_space", "networking_areas", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Legal and Judicial Conference Center",
    name_ar: "مركز المؤتمرات القانونية والقضائية",
    venue_type: "convention_center",
    capacity: 300,
    price_per_event: 9000,
    city: "Dammam",
    address: "Justice Complex, Dammam",
    phone: "+966 13 841 8000",
    email: "legal@judicial.com",
    description: "Specialized venue for legal conferences, judicial seminars, and law enforcement training programs",
    amenities: ["legal_focus", "judicial_facilities", "law_enforcement", "training_programs", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Healthcare Innovation Conference Hall",
    name_ar: "قاعة مؤتمرات الابتكار الصحي",
    venue_type: "convention_center",
    capacity: 350,
    price_per_event: 9500,
    city: "Al Khobar",
    address: "Medical City, Al Khobar",
    phone: "+966 13 897 3000",
    email: "healthcare@innovation.com",
    description: "Medical innovation center with telemedicine facilities, medical simulation areas, and healthcare technology showcases",
    amenities: ["medical_innovation", "telemedicine", "simulation_areas", "healthcare_technology", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Engineering Excellence Conference Center",
    name_ar: "مركز مؤتمرات التميز الهندسي",
    venue_type: "convention_center",
    capacity: 400,
    price_per_event: 10000,
    city: "Dhahran",
    address: "Engineering Complex, Dhahran",
    phone: "+966 13 874 2000",
    email: "engineering@excellence.com",
    description: "Engineering-focused venue with technical presentation capabilities, CAD facilities, and engineering project showcases",
    amenities: ["engineering_focus", "technical_presentation", "cad_facilities", "project_showcase", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Tourism and Hospitality Conference Hall",
    name_ar: "قاعة مؤتمرات السياحة والضيافة",
    venue_type: "convention_center",
    capacity: 280,
    price_per_event: 8000,
    city: "Al Khobar",
    address: "Tourism District, Al Khobar",
    phone: "+966 13 891 5000",
    email: "tourism@hospitality.com",
    description: "Tourism industry venue with hospitality showcase areas, travel exhibition space, and cultural presentation facilities",
    amenities: ["tourism_focus", "hospitality_showcase", "travel_exhibition", "cultural_presentation", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Logistics and Supply Chain Conference Center",
    name_ar: "مركز مؤتمرات اللوجستيات وسلسلة التوريد",
    venue_type: "convention_center",
    capacity: 450,
    price_per_event: 11500,
    city: "Dammam",
    address: "Logistics Hub, Dammam",
    phone: "+966 13 847 1000",
    email: "logistics@supply.com",
    description: "Logistics industry venue with supply chain simulation areas, transportation exhibits, and warehouse management showcases",
    amenities: ["logistics_focus", "supply_chain", "transportation_exhibits", "warehouse_management", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Renewable Energy Conference Hall",
    name_ar: "قاعة مؤتمرات الطاقة المتجددة",
    venue_type: "convention_center",
    capacity: 350,
    price_per_event: 9500,
    city: "Dhahran",
    address: "Energy Research Center, Dhahran",
    phone: "+966 13 873 4000",
    email: "renewable@energy.com",
    description: "Green energy-focused venue with solar panel displays, wind energy exhibits, and sustainability demonstration areas",
    amenities: ["renewable_energy", "solar_displays", "wind_exhibits", "sustainability_demo", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Telecommunications Conference Center",
    name_ar: "مركز مؤتمرات الاتصالات",
    venue_type: "convention_center",
    capacity: 320,
    price_per_event: 8800,
    city: "Al Khobar",
    address: "Telecom Valley, Al Khobar",
    phone: "+966 13 898 6000",
    email: "telecom@conferences.com",
    description: "Telecommunications industry venue with 5G demonstration areas, satellite communication exhibits, and digital technology showcases",
    amenities: ["telecom_focus", "5g_demo", "satellite_exhibits", "digital_technology", "av_equipment", "catering", "parking", "wifi"],
  },
  {
    name: "Automotive Industry Conference Hall",
    name_ar: "قاعة مؤتمرات صناعة السيارات",
    venue_type: "convention_center",
    capacity: 380,
    price_per_event: 9800,
    city: "Dammam",
    address: "Industrial Zone, Dammam",
    phone: "+966 13 846 2000",
    email: "automotive@industry.com",
    description: "Automotive-focused venue with vehicle displays, manufacturing simulation areas, and automotive technology exhibits",
    amenities: ["automotive_focus", "vehicle_displays", "manufacturing_simulation", "auto_technology", "av_equipment", "catering", "parking", "wifi"],
  },

  // ***** CULTURAL VENUES (20 venues) *****
  {
    name: "Dammam Museum",
    name_ar: "متحف الدمام",
    venue_type: "cultural_center",
    capacity: 300,
    price_per_event: 8000,
    city: "Dammam",
    address: "King Abdullah Park, Dammam Corniche",
    phone: "+966 13 832 7000",
    email: "info@dammammuseum.org.sa",
    description: "Regional museum with 5 floors, 7 exhibition halls covering prehistoric, pre-Islamic, and heritage artifacts with restoration facilities",
    amenities: ["exhibition_halls", "restoration_facilities", "heritage_artifacts", "educational_programs", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Heritage Village Dammam",
    name_ar: "القرية التراثية الدمام",
    venue_type: "cultural_center",
    capacity: 500,
    price_per_event: 12000,
    city: "Dammam",
    address: "Heritage Quarter, Dammam",
    phone: "+966 13 838 5000",
    email: "heritage@village.org.sa",
    description: "Traditional Saudi architecture showcase with cultural exhibits, historical artifacts, and authentic heritage experiences",
    amenities: ["traditional_architecture", "cultural_exhibits", "historical_artifacts", "heritage_experiences", "outdoor_spaces", "parking", "wifi"],
  },
  {
    name: "Prince Sultan Science & Technology Center (SciTech)",
    name_ar: "مركز الأمير سلطان للعلوم والتقنية",
    venue_type: "cultural_center",
    capacity: 400,
    price_per_event: 10000,
    city: "Al Khobar",
    address: "Al Khobar Corniche, Near Water Tower",
    phone: "+966 13 898 7000",
    email: "scitech@khobar.org.sa",
    description: "Interactive science center with 7 exhibition halls, IMAX theater, observatory, and educational programs",
    amenities: ["interactive_exhibits", "imax_theater", "observatory", "educational_programs", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Dawi Gallery",
    name_ar: "معرض داوي",
    venue_type: "cultural_center",
    capacity: 150,
    price_per_event: 5000,
    city: "Al Khobar",
    address: "King Saud Street and 22nd Street, Al Khobar",
    phone: "+966 13 895 2000",
    email: "info@dawigallery.com",
    description: "Contemporary art gallery supporting local artists with cutting-edge exhibitions and graffiti art projects",
    amenities: ["contemporary_art", "local_artists", "cutting_edge_exhibitions", "graffiti_projects", "gallery_space", "parking", "wifi"],
  },
  {
    name: "Gallery Azman",
    name_ar: "معرض عزمان",
    venue_type: "cultural_center",
    capacity: 120,
    price_per_event: 4500,
    city: "Al Khobar",
    address: "5th Floor, Prince Fawaz Street, Al Khobar",
    phone: "+966 13 893 1500",
    email: "info@gallery-azman.com",
    description: "Newest art gallery in the region with large exhibition space and contemporary art focus",
    amenities: ["large_exhibition_space", "contemporary_art", "modern_facilities", "gallery_events", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Arab Heritage Gallery",
    name_ar: "معرض التراث العربي",
    venue_type: "cultural_center",
    capacity: 100,
    price_per_event: 4000,
    city: "Al Khobar",
    address: "Heritage District, Al Khobar",
    phone: "+966 13 892 8000",
    email: "arab@heritage.com",
    description: "First gallery in the area (est. 1979) featuring solo and group exhibitions by local artists and craftsmen",
    amenities: ["historic_gallery", "local_artists", "traditional_crafts", "exhibition_space", "cultural_programs", "parking", "wifi"],
  },
  {
    name: "Desert Designs Gallery",
    name_ar: "معرض تصاميم الصحراء",
    venue_type: "cultural_center",
    capacity: 80,
    price_per_event: 3500,
    city: "Al Khobar",
    address: "3616 Custodian of the Two Holy Mosques Road",
    phone: "+966 13 897 6000",
    email: "info@desertdesigns.com",
    description: "Family business since 1990 known for annual 'Loud Art' exhibition and classical Middle Eastern art",
    amenities: ["family_business", "classical_art", "loud_art_exhibition", "middle_eastern_focus", "gallery_space", "parking", "wifi"],
  },
  {
    name: "Saudi Arabian Society for Culture and Art (SACSA) - Dammam",
    name_ar: "الجمعية العربية السعودية للثقافة والفنون - الدمام",
    venue_type: "cultural_center",
    capacity: 200,
    price_per_event: 6000,
    city: "Dammam",
    address: "Cultural District, Dammam",
    phone: "+966 13 841 3000",
    email: "dammam@sacsa.org.sa",
    description: "One of SACSA's largest locations supporting Saudi artists and developing new talent with regular exhibitions",
    amenities: ["artist_support", "talent_development", "regular_exhibitions", "cultural_programs", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Eastern Province Cultural Foundation",
    name_ar: "مؤسسة المنطقة الشرقية الثقافية",
    venue_type: "cultural_center",
    capacity: 250,
    price_per_event: 7000,
    city: "Dammam",
    address: "King Fahd Cultural Center, Dammam",
    phone: "+966 13 844 5000",
    email: "foundation@epcf.org.sa",
    description: "Cultural foundation promoting Eastern Province heritage, arts, and literature with performance spaces",
    amenities: ["heritage_promotion", "performance_spaces", "literature_programs", "arts_education", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Coral Island Heritage Center",
    name_ar: "مركز تراث جزيرة المرجان",
    venue_type: "cultural_center",
    capacity: 180,
    price_per_event: 5500,
    city: "Dammam",
    address: "Coral Island, Half Moon Bay",
    phone: "+966 13 857 2000",
    email: "coral@heritage.com",
    description: "Island heritage center with traditional Saudi crafts, architecture exhibits, and cultural practices demonstrations",
    amenities: ["traditional_crafts", "architecture_exhibits", "cultural_demonstrations", "island_location", "outdoor_spaces", "parking", "wifi"],
  },

  // Additional 10 cultural venues
  {
    name: "Frame Gallery",
    name_ar: "معرض الإطار",
    venue_type: "cultural_center",
    capacity: 90,
    price_per_event: 3800,
    city: "Al Khobar",
    address: "Art District, Al Khobar",
    phone: "+966 13 894 3000",
    email: "frame@gallery.com",
    description: "Contemporary frame gallery showcasing modern art installations and photographic exhibitions",
    amenities: ["modern_art", "photographic_exhibitions", "frame_collections", "gallery_space", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Silver Museum",
    name_ar: "متحف الفضة",
    venue_type: "cultural_center",
    capacity: 70,
    price_per_event: 3200,
    city: "Al Khobar",
    address: "Jewelry District, Al Khobar",
    phone: "+966 13 896 5000",
    email: "silver@museum.com",
    description: "Specialized museum featuring traditional silver jewelry, artifacts, and metalwork from the Eastern Province",
    amenities: ["silver_collections", "traditional_jewelry", "metalwork_exhibits", "artifact_displays", "educational_tours", "parking", "wifi"],
  },
  {
    name: "Sugar Lab Creative Space",
    name_ar: "مساحة السكر الإبداعية",
    venue_type: "cultural_center",
    capacity: 60,
    price_per_event: 2800,
    city: "Al Khobar",
    address: "Creative Quarter, Al Khobar",
    phone: "+966 13 899 1000",
    email: "sugar@lab.com",
    description: "Innovative creative space for experimental art, workshops, and artistic collaborations",
    amenities: ["experimental_art", "artistic_workshops", "creative_collaborations", "innovation_space", "flexible_layout", "parking", "wifi"],
  },
  {
    name: "Najdi Heritage House",
    name_ar: "بيت التراث النجدي",
    venue_type: "cultural_center",
    capacity: 120,
    price_per_event: 4200,
    city: "Dammam",
    address: "Old Quarter, Dammam",
    phone: "+966 13 836 7000",
    email: "najdi@heritage.com",
    description: "Traditional Najdi architecture house converted into cultural center showcasing central Arabian heritage",
    amenities: ["najdi_architecture", "central_arabian_heritage", "traditional_house", "cultural_exhibitions", "heritage_programs", "parking", "wifi"],
  },
  {
    name: "Maritime Heritage Museum",
    name_ar: "متحف التراث البحري",
    venue_type: "cultural_center",
    capacity: 150,
    price_per_event: 5000,
    city: "Dammam",
    address: "Port District, Dammam",
    phone: "+966 13 833 6000",
    email: "maritime@heritage.com",
    description: "Coastal heritage museum featuring traditional dhows, fishing techniques, and pearling history of the Gulf",
    amenities: ["maritime_exhibits", "traditional_dhows", "fishing_heritage", "pearling_history", "coastal_culture", "parking", "wifi"],
  },
  {
    name: "Eastern Province Archaeological Center",
    name_ar: "مركز الآثار للمنطقة الشرقية",
    venue_type: "cultural_center",
    capacity: 100,
    price_per_event: 4000,
    city: "Dhahran",
    address: "Archaeological District, Dhahran",
    phone: "+966 13 872 1000",
    email: "archaeology@ep.com",
    description: "Archaeological research center with ancient artifacts, excavation displays, and historical research facilities",
    amenities: ["ancient_artifacts", "excavation_displays", "research_facilities", "archaeological_tours", "educational_programs", "parking", "wifi"],
  },
  {
    name: "Bedouin Culture Center",
    name_ar: "مركز الثقافة البدوية",
    venue_type: "cultural_center",
    capacity: 200,
    price_per_event: 6000,
    city: "Dammam",
    address: "Desert Heritage Quarter, Dammam",
    phone: "+966 13 845 8000",
    email: "bedouin@culture.com",
    description: "Desert culture center showcasing Bedouin traditions, camel heritage, and nomadic lifestyle exhibitions",
    amenities: ["bedouin_traditions", "camel_heritage", "nomadic_exhibitions", "desert_culture", "traditional_tents", "parking", "wifi"],
  },
  {
    name: "Contemporary Art Space Khobar",
    name_ar: "مساحة الفن المعاصر الخبر",
    venue_type: "cultural_center",
    capacity: 130,
    price_per_event: 4500,
    city: "Al Khobar",
    address: "Modern Art District, Al Khobar",
    phone: "+966 13 891 7000",
    email: "contemporary@art.com",
    description: "Modern art space featuring contemporary Saudi and international artists with rotating exhibitions",
    amenities: ["contemporary_art", "rotating_exhibitions", "international_artists", "modern_space", "art_workshops", "parking", "wifi"],
  },
  {
    name: "Islamic Arts and Calligraphy Center",
    name_ar: "مركز الفنون الإسلامية والخط العربي",
    venue_type: "cultural_center",
    capacity: 160,
    price_per_event: 5200,
    city: "Dammam",
    address: "Islamic Arts Quarter, Dammam",
    phone: "+966 13 842 9000",
    email: "islamic@arts.com",
    description: "Specialized center for Islamic arts, Arabic calligraphy, and geometric pattern exhibitions with workshops",
    amenities: ["islamic_arts", "arabic_calligraphy", "geometric_patterns", "art_workshops", "cultural_education", "parking", "wifi"],
  },
  {
    name: "Youth Cultural Center",
    name_ar: "مركز الشباب الثقافي",
    venue_type: "cultural_center",
    capacity: 300,
    price_per_event: 7500,
    city: "Al Khobar",
    address: "Youth District, Al Khobar",
    phone: "+966 13 898 4000",
    email: "youth@cultural.com",
    description: "Dynamic cultural center for youth programs, modern art, music events, and creative workshops",
    amenities: ["youth_programs", "modern_art", "music_events", "creative_workshops", "performance_space", "parking", "wifi"],
  },

  // ***** SHOPPING MALLS & ENTERTAINMENT CENTERS (40 venues) *****
  {
    name: "Al Shatea Mall",
    name_ar: "الشاطئ مول",
    venue_type: "mall",
    capacity: 800,
    price_per_event: 15000,
    city: "Dammam",
    address: "Al Ashriah Street, Ash Shati Ash Sharqi",
    phone: "+966 13 832 9000",
    email: "events@alshareamall.com",
    description: "Over 300 retail stores with Mega Land indoor amusement park, diverse food court, and family entertainment center",
    amenities: ["300_stores", "amusement_park", "food_court", "family_entertainment", "shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Mall of Dhahran",
    name_ar: "مول الظهران",
    venue_type: "mall",
    capacity: 1200,
    price_per_event: 25000,
    city: "Dhahran",
    address: "Prince Mohammed Bin Fahd Branch Road, Al Shifa",
    phone: "+966 13 891 8000",
    email: "events@mallofdhahran.com",
    description: "220,000+ square meters with 350+ stores, AMC Cinema with premium seating, and Sparky's family center",
    amenities: ["350_stores", "amc_cinema", "family_center", "premium_facilities", "shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Marina Mall",
    name_ar: "مول المارينا",
    venue_type: "mall",
    capacity: 600,
    price_per_event: 12000,
    city: "Dammam",
    address: "Khaleej Road, As Salam, Dammam Corniche",
    phone: "+966 13 834 7000",
    email: "events@marinamall.com",
    description: "120+ stores across two floors with 5D cinema (first in Eastern Province), seaside location with Gulf views",
    amenities: ["120_stores", "5d_cinema", "seaside_location", "gulf_views", "entertainment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Dareen Mall",
    name_ar: "مول دارين",
    venue_type: "mall",
    capacity: 500,
    price_per_event: 10000,
    city: "Dammam",
    address: "Khaleej Road, Al Aziziyah, opposite Seihat Lake",
    phone: "+966 13 837 6000",
    email: "events@dareenmall.com",
    description: "Modern family-focused design with scenic lake views, Splash Sparkys water-themed zone, and Meowcafe",
    amenities: ["family_focused", "lake_views", "water_theme_zone", "animal_cafe", "entertainment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Nakheel Mall",
    name_ar: "مول النخيل",
    venue_type: "mall",
    capacity: 700,
    price_per_event: 14000,
    city: "Dammam",
    address: "Al Nakheel District, Dammam",
    phone: "+966 13 845 5000",
    email: "events@nakheelmall.com",
    description: "Cenomi Centers mall with wide range of shopping and dining, parking for 1,400+ cars, and Cenomi Plus App",
    amenities: ["cenomi_centers", "wide_shopping_range", "large_parking", "mobile_app", "shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "West Avenue Mall",
    name_ar: "مول الجادة الغربية",
    venue_type: "mall",
    capacity: 450,
    price_per_event: 9000,
    city: "Dammam",
    address: "West Avenue, Dammam",
    phone: "+966 13 839 8000",
    email: "events@westavenue.com",
    description: "88+ outlets including Carrefour, SACO, Zara, Adidas, Nike with comprehensive shopping and entertainment",
    amenities: ["88_outlets", "international_brands", "hypermarket", "comprehensive_shopping", "entertainment", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Othaim Mall Dammam",
    name_ar: "مول العثيم الدمام",
    venue_type: "mall",
    capacity: 900,
    price_per_event: 18000,
    city: "Dammam",
    address: "King Fahd Road, Dammam",
    phone: "+966 13 848 2000",
    email: "events@othaimmall.com",
    description: "350+ diverse stores with Othaim Amusement, family entertainment areas, hypermarket, and restaurants",
    amenities: ["350_stores", "amusement_center", "family_entertainment", "hypermarket", "restaurants", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Lulu Mall Dammam",
    name_ar: "مول لولو الدمام",
    venue_type: "mall",
    capacity: 400,
    price_per_event: 8000,
    city: "Dammam",
    address: "Al Manar District, Dammam",
    phone: "+966 13 843 1000",
    email: "events@lulumall.com",
    description: "Shopping and entertainment destination with outstanding facilities, open 8:00 AM - 10:45 PM",
    amenities: ["outstanding_facilities", "extended_hours", "shopping_entertainment", "family_friendly", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Rashid Mall Al Khobar",
    name_ar: "مول الراشد الخبر",
    venue_type: "mall",
    capacity: 650,
    price_per_event: 13000,
    city: "Al Khobar",
    address: "Prince Faisal Road, Al Khobar",
    phone: "+966 13 896 9000",
    email: "events@rashidmall.com",
    description: "Premier shopping destination with luxury brands, family entertainment, and direct hotel access",
    amenities: ["luxury_brands", "family_entertainment", "hotel_access", "premier_shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "City Center Al Khobar",
    name_ar: "سيتي سنتر الخبر",
    venue_type: "mall",
    capacity: 550,
    price_per_event: 11000,
    city: "Al Khobar",
    address: "City Center District, Al Khobar",
    phone: "+966 13 899 7000",
    email: "events@citycenter.com",
    description: "Urban shopping center with modern facilities, entertainment zones, and central location",
    amenities: ["urban_shopping", "modern_facilities", "entertainment_zones", "central_location", "parking", "wifi", "air_conditioning"],
  },

  // Additional 10 shopping and entertainment centers
  {
    name: "Cobra Entertainment City",
    name_ar: "مدينة الكوبرا الترفيهية",
    venue_type: "entertainment_venue",
    capacity: 1000,
    price_per_event: 20000,
    city: "Dammam",
    address: "King Fahd Park, Dammam",
    phone: "+966 13 846 3000",
    email: "events@cobraentertainment.com",
    description: "Entertainment complex with zoo, skating rink, cinema, theatre, Snow City, rocket rides, and cobra train",
    amenities: ["zoo", "skating_rink", "cinema", "theatre", "snow_city", "amusement_rides", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Adventure World Dammam",
    name_ar: "عالم المغامرات الدمام",
    venue_type: "entertainment_venue",
    capacity: 600,
    price_per_event: 12000,
    city: "Dammam",
    address: "Entertainment District, Dammam",
    phone: "+966 13 841 9000",
    email: "events@adventureworld.com",
    description: "Amusement center with bumper cars, high-level bowling alley, video games, and unique entertainment experiences",
    amenities: ["bumper_cars", "bowling_alley", "video_games", "unique_entertainment", "family_activities", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Skyzone Dammam",
    name_ar: "سكاي زون الدمام",
    venue_type: "entertainment_venue",
    capacity: 300,
    price_per_event: 7000,
    city: "Dammam",
    address: "Sports City, Dammam",
    phone: "+966 13 847 5000",
    email: "events@skyzone.com",
    description: "Trampoline park and entertainment center with aerial activities, fitness programs, and birthday party packages",
    amenities: ["trampoline_park", "aerial_activities", "fitness_programs", "birthday_packages", "youth_activities", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Galaxy Mall",
    name_ar: "مول المجرة",
    venue_type: "mall",
    capacity: 350,
    price_per_event: 7500,
    city: "Al Khobar",
    address: "Galaxy District, Al Khobar",
    phone: "+966 13 893 2000",
    email: "events@galaxymall.com",
    description: "Space-themed shopping mall with cosmic entertainment, gaming zones, and futuristic design",
    amenities: ["space_theme", "cosmic_entertainment", "gaming_zones", "futuristic_design", "shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Palm Grove Shopping Center",
    name_ar: "مركز بستان النخيل التجاري",
    venue_type: "mall",
    capacity: 280,
    price_per_event: 6000,
    city: "Dammam",
    address: "Palm District, Dammam",
    phone: "+966 13 838 4000",
    email: "events@palmgrove.com",
    description: "Natural-themed shopping center with palm grove atmosphere, outdoor shopping areas, and family facilities",
    amenities: ["natural_theme", "palm_atmosphere", "outdoor_shopping", "family_facilities", "green_spaces", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Waterfront Entertainment Complex",
    name_ar: "مجمع الواجهة البحرية الترفيهي",
    venue_type: "entertainment_venue",
    capacity: 800,
    price_per_event: 16000,
    city: "Al Khobar",
    address: "Corniche Waterfront, Al Khobar",
    phone: "+966 13 897 8000",
    email: "events@waterfront.com",
    description: "Seaside entertainment complex with water activities, marine shows, aquarium, and beachfront venues",
    amenities: ["water_activities", "marine_shows", "aquarium", "beachfront_venues", "seaside_location", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Crystal Plaza Shopping Mall",
    name_ar: "مول كريستال بلازا",
    venue_type: "mall",
    capacity: 400,
    price_per_event: 8500,
    city: "Dammam",
    address: "Crystal District, Dammam",
    phone: "+966 13 844 7000",
    email: "events@crystalplaza.com",
    description: "Elegant shopping destination with crystal-inspired design, luxury boutiques, and premium dining",
    amenities: ["crystal_design", "luxury_boutiques", "premium_dining", "elegant_atmosphere", "shopping", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Family Fun Center",
    name_ar: "مركز المرح العائلي",
    venue_type: "entertainment_venue",
    capacity: 500,
    price_per_event: 10000,
    city: "Al Khobar",
    address: "Family District, Al Khobar",
    phone: "+966 13 892 6000",
    email: "events@familyfun.com",
    description: "Family entertainment center with kids' zones, arcade games, mini golf, laser tag, and party facilities",
    amenities: ["kids_zones", "arcade_games", "mini_golf", "laser_tag", "party_facilities", "family_entertainment", "parking", "wifi"],
  },
  {
    name: "Sports and Recreation Mall",
    name_ar: "مول الرياضة والترفيه",
    venue_type: "mall",
    capacity: 600,
    price_per_event: 12000,
    city: "Dammam",
    address: "Sports City, Dammam",
    phone: "+966 13 849 1000",
    email: "events@sportsmall.com",
    description: "Sports-themed shopping destination with sports equipment stores, fitness centers, and athletic facilities",
    amenities: ["sports_theme", "equipment_stores", "fitness_centers", "athletic_facilities", "sports_activities", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Heritage Souk and Entertainment",
    name_ar: "سوق التراث والترفيه",
    venue_type: "entertainment_venue",
    capacity: 400,
    price_per_event: 9000,
    city: "Dammam",
    address: "Heritage Quarter, Dammam",
    phone: "+966 13 836 8000",
    email: "events@heritagesouk.com",
    description: "Traditional market with modern entertainment, cultural performances, handicraft workshops, and authentic dining",
    amenities: ["traditional_market", "cultural_performances", "handicraft_workshops", "authentic_dining", "heritage_experience", "parking", "wifi"],
  },

  // Additional 20 venues across various categories to reach 200 total
  {
    name: "Golden Sands Beach Resort",
    name_ar: "منتجع الرمال الذهبية",
    venue_type: "outdoor",
    capacity: 300,
    price_per_event: 8000,
    city: "Al Khobar",
    address: "Half Moon Bay, Al Khobar",
    phone: "+966 13 895 4000",
    email: "events@goldensands.com",
    description: "Beachfront resort with private beach access, water sports facilities, and sunset event spaces",
    amenities: ["private_beach", "water_sports", "sunset_spaces", "beachfront_location", "outdoor_activities", "parking", "wifi"],
  },
  {
    name: "Desert Rose Event Gardens",
    name_ar: "حدائق وردة الصحراء للفعاليات",
    venue_type: "outdoor",
    capacity: 500,
    price_per_event: 12000,
    city: "Dammam",
    address: "Desert Highway, Dammam",
    phone: "+966 13 847 2000",
    email: "events@desertrose.com",
    description: "Desert garden venue with Bedouin-style tents, traditional seating, and stargazing facilities",
    amenities: ["bedouin_tents", "traditional_seating", "stargazing", "desert_atmosphere", "outdoor_events", "parking", "wifi"],
  },
  {
    name: "King Fahd Sports Complex",
    name_ar: "مجمع الملك فهد الرياضي",
    venue_type: "sports_center",
    capacity: 2000,
    price_per_event: 30000,
    city: "Dammam",
    address: "Sports City, Dammam",
    phone: "+966 13 849 8000",
    email: "events@kfsports.com",
    description: "Major sports complex with stadium, multiple courts, fitness facilities, and event hosting capabilities",
    amenities: ["stadium", "multiple_courts", "fitness_facilities", "sports_events", "large_capacity", "parking", "wifi", "air_conditioning"],
  },
  {
    name: "Al Khobar Yacht Club",
    name_ar: "نادي اليخوت الخبر",
    venue_type: "sports_center",
    capacity: 400,
    price_per_event: 15000,
    city: "Al Khobar",
    address: "Marina District, Al Khobar",
    phone: "+966 13 898 5000",
    email: "events@yachtclub.com",
    description: "Exclusive yacht club with marina views, sailing facilities, and waterfront event spaces",
    amenities: ["marina_views", "sailing_facilities", "waterfront_events", "yacht_club", "exclusive_access", "parking", "wifi"],
  },
  {
    name: "Eastern Province Community Center",
    name_ar: "مركز المجتمع للمنطقة الشرقية",
    venue_type: "community_center",
    capacity: 600,
    price_per_event: 10000,
    city: "Dammam",
    address: "Community District, Dammam",
    phone: "+966 13 842 4000",
    email: "events@epcommunity.com",
    description: "Community center with multipurpose halls, social services, and neighborhood event facilities",
    amenities: ["multipurpose_halls", "social_services", "neighborhood_events", "community_programs", "flexible_spaces", "parking", "wifi"],
  },
  {
    name: "Al Khobar Community Hall",
    name_ar: "قاعة مجتمع الخبر",
    venue_type: "community_center",
    capacity: 350,
    price_per_event: 7000,
    city: "Al Khobar",
    address: "Residential District, Al Khobar",
    phone: "+966 13 894 6000",
    email: "events@khobarcommunity.com",
    description: "Local community hall serving residential areas with meeting rooms and social event spaces",
    amenities: ["meeting_rooms", "social_events", "residential_service", "community_activities", "local_programs", "parking", "wifi"],
  },
  {
    name: "Dhahran Hills Country Club",
    name_ar: "نادي تلال الظهران الريفي",
    venue_type: "sports_center",
    capacity: 250,
    price_per_event: 12000,
    city: "Dhahran",
    address: "Dhahran Hills, Dhahran",
    phone: "+966 13 873 7000",
    email: "events@dhahranclub.com",
    description: "Exclusive country club with golf course, tennis courts, and upscale event facilities",
    amenities: ["golf_course", "tennis_courts", "upscale_facilities", "country_club", "exclusive_membership", "parking", "wifi"],
  },
  {
    name: "Dammam Corniche Event Plaza",
    name_ar: "ساحة فعاليات كورنيش الدمام",
    venue_type: "outdoor",
    capacity: 1000,
    price_per_event: 20000,
    city: "Dammam",
    address: "Corniche Waterfront, Dammam",
    phone: "+966 13 833 9000",
    email: "events@cornicheplaza.com",
    description: "Waterfront event plaza with Gulf views, outdoor stages, and public gathering spaces",
    amenities: ["gulf_views", "outdoor_stages", "public_gathering", "waterfront_location", "open_air_events", "parking", "wifi"],
  },
  {
    name: "Heritage Majlis Hall",
    name_ar: "قاعة المجلس التراثي",
    venue_type: "cultural_center",
    capacity: 150,
    price_per_event: 5000,
    city: "Dammam",
    address: "Traditional Quarter, Dammam",
    phone: "+966 13 835 8000",
    email: "events@heritagemajlis.com",
    description: "Traditional majlis-style meeting hall with authentic Arabian seating and cultural atmosphere",
    amenities: ["traditional_majlis", "arabian_seating", "cultural_atmosphere", "heritage_design", "authentic_decor", "parking", "wifi"],
  },
  {
    name: "Innovation Hub Conference Center",
    name_ar: "مركز مؤتمرات مركز الابتكار",
    venue_type: "convention_center",
    capacity: 300,
    price_per_event: 8000,
    city: "Al Khobar",
    address: "Technology Park, Al Khobar",
    phone: "+966 13 891 4000",
    email: "events@innovationhub.com",
    description: "Tech-focused conference center with startup showcase areas, innovation labs, and modern facilities",
    amenities: ["startup_showcase", "innovation_labs", "tech_focus", "modern_facilities", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Gulf International School Auditorium",
    name_ar: "قاعة مدرسة الخليج الدولية",
    venue_type: "convention_center",
    capacity: 400,
    price_per_event: 7000,
    city: "Dammam",
    address: "Educational District, Dammam",
    phone: "+966 13 846 5000",
    email: "events@gulfschool.edu.sa",
    description: "School auditorium with educational facilities, performance stage, and community event capabilities",
    amenities: ["educational_facilities", "performance_stage", "community_events", "school_auditorium", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Dammam International Hotel",
    name_ar: "فندق الدمام الدولي",
    venue_type: "hotel",
    capacity: 300,
    price_per_event: 8000,
    city: "Dammam",
    address: "International District, Dammam",
    phone: "+966 13 834 6000",
    email: "events@dammaminternational.com",
    description: "International business hotel with conference facilities, executive meeting rooms, and corporate event services",
    amenities: ["conference_facilities", "executive_rooms", "corporate_services", "business_hotel", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Emerald Garden Wedding Palace",
    name_ar: "قصر حديقة الزمرد للأفراح",
    venue_type: "wedding_hall",
    capacity: 600,
    price_per_event: 18000,
    city: "Al Khobar",
    address: "Garden District, Al Khobar",
    phone: "+966 13 896 3000",
    email: "events@emeraldgarden.com",
    description: "Garden palace wedding venue with outdoor ceremony spaces, botanical gardens, and natural elegance",
    amenities: ["outdoor_ceremony", "botanical_gardens", "natural_elegance", "garden_palace", "catering", "parking", "wifi"],
  },
  {
    name: "Executive Business Center",
    name_ar: "مركز الأعمال التنفيذي",
    venue_type: "convention_center",
    capacity: 200,
    price_per_event: 6000,
    city: "Al Khobar",
    address: "Executive Tower, Al Khobar",
    phone: "+966 13 899 2000",
    email: "events@executivecenter.com",
    description: "Upscale business center with boardrooms, presentation facilities, and executive meeting services",
    amenities: ["boardrooms", "presentation_facilities", "executive_services", "upscale_business", "av_equipment", "parking", "wifi"],
  },
  {
    name: "Seaside Event Gardens",
    name_ar: "حدائق الفعاليات الساحلية",
    venue_type: "outdoor",
    capacity: 400,
    price_per_event: 10000,
    city: "Dammam",
    address: "Seaside Gardens, Dammam",
    phone: "+966 13 837 1000",
    email: "events@seasidegardens.com",
    description: "Coastal garden venue with sea breezes, tropical landscaping, and outdoor event pavilions",
    amenities: ["sea_breezes", "tropical_landscaping", "outdoor_pavilions", "coastal_garden", "natural_setting", "parking", "wifi"],
  },
  {
    name: "Al Fanar Lighthouse Events",
    name_ar: "فعاليات منارة الفنار",
    venue_type: "outdoor",
    capacity: 250,
    price_per_event: 7000,
    city: "Al Khobar",
    address: "Lighthouse Point, Al Khobar",
    phone: "+966 13 893 5000",
    email: "events@fanar.com",
    description: "Unique lighthouse venue with panoramic sea views, maritime atmosphere, and coastal event spaces",
    amenities: ["panoramic_views", "maritime_atmosphere", "lighthouse_venue", "coastal_events", "unique_setting", "parking", "wifi"],
  },
  {
    name: "Royal Garden Palace",
    name_ar: "قصر الحديقة الملكية",
    venue_type: "wedding_hall",
    capacity: 800,
    price_per_event: 25000,
    city: "Dammam",
    address: "Royal Gardens, Dammam",
    phone: "+966 13 848 7000",
    email: "events@royalgarden.com",
    description: "Magnificent palace with royal gardens, fountain displays, and grand celebration halls",
    amenities: ["royal_gardens", "fountain_displays", "grand_halls", "palace_setting", "magnificent_design", "parking", "wifi"],
  },
  {
    name: "Modern Art Gallery Space",
    name_ar: "مساحة معرض الفن الحديث",
    venue_type: "cultural_center",
    capacity: 120,
    price_per_event: 4000,
    city: "Al Khobar",
    address: "Art Quarter, Al Khobar",
    phone: "+966 13 897 4000",
    email: "events@modernart.com",
    description: "Contemporary gallery space with rotating exhibitions, artist workshops, and creative event hosting",
    amenities: ["rotating_exhibitions", "artist_workshops", "creative_events", "contemporary_gallery", "art_space", "parking", "wifi"],
  },
  {
    name: "Oasis Convention Center",
    name_ar: "مركز مؤتمرات الواحة",
    venue_type: "convention_center",
    capacity: 500,
    price_per_event: 12000,
    city: "Dammam",
    address: "Oasis District, Dammam",
    phone: "+966 13 845 3000",
    email: "events@oasisconvention.com",
    description: "Desert oasis-themed convention center with palm garden courtyards and natural lighting",
    amenities: ["palm_gardens", "natural_lighting", "desert_theme", "convention_facilities", "courtyards", "parking", "wifi"],
  },
  {
    name: "Infinity Shopping Plaza",
    name_ar: "بلازا إنفينيتي التجارية",
    venue_type: "mall",
    capacity: 300,
    price_per_event: 6500,
    city: "Al Khobar",
    address: "Infinity District, Al Khobar",
    phone: "+966 13 892 1000",
    email: "events@infinityplaza.com",
    description: "Modern shopping plaza with infinity pool features, rooftop events, and contemporary design",
    amenities: ["infinity_features", "rooftop_events", "contemporary_design", "modern_plaza", "shopping", "parking", "wifi"],
  },
];

async function addDammamVenues() {
  try {
    console.log('🚀 Starting to add 200 Dammam venues...');
    
    // Process in batches of 10 venues
    const batchSize = 10;
    let addedCount = 0;
    
    for (let i = 0; i < dammamVenues.length; i += batchSize) {
      const batch = dammamVenues.slice(i, i + batchSize);
      
      console.log(`📦 Processing batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(dammamVenues.length / batchSize)}...`);
      
      // Insert batch
      await db.insert(venues).values(batch);
      addedCount += batch.length;
      
      console.log(`✅ Added ${batch.length} venues. Total: ${addedCount}/${dammamVenues.length}`);
      
      // Brief pause between batches
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    console.log(`🎉 Successfully added all ${addedCount} Dammam venues!`);
    
    // Verify the additions
    const result = await db
      .execute(sql`SELECT COUNT(*) as total FROM venues WHERE city ILIKE 'dammam' OR city ILIKE 'al khobar' OR city ILIKE 'dhahran'`);
    
    console.log(`📊 Total Dammam area venues in database: ${result.rows[0].total}`);
    
  } catch (error) {
    console.error('❌ Error adding Dammam venues:', error);
    throw error;
  }
}

// Run the script
addDammamVenues().then(() => {
  console.log('✨ Dammam venues addition completed!');
  process.exit(0);
}).catch((error) => {
  console.error('💥 Failed to add Dammam venues:', error);
  process.exit(1);
});